// samples/vue/src/components/GraphQL/GraphQL-ConnectedDemo.vue
<!--
-->
<template>
  <div data-e2e-id="graphql-connected">
    <h2>GraphQL Connected Demo</h2>

    <p>
      Connected GraphQL executes GraphQL queries directly against the Sitecore GraphQL endpoint. You
      can review the query execution in the browser devtools network tab. Note that Apollo Client
      maintains a query cache - so the same query will not execute twice (i.e. after route changes)
      unless either the page is refreshed, or the <em>fetch policy</em> is set to not use the cache.
      Consult the Apollo documentation for details.
    </p>

    <p v-if="loading" class="alert alert-info">GraphQL query is executing...</p>
    <p v-if="error" class="alert alert-danger">GraphQL query error: {{ error.toString() }}</p>
    <div v-if="!loading && result && result.datasource">
      <h4>Datasource Item (via Connected GraphQL)</h4>
      id: {{ result.datasource.id }}
      <br />
      name: {{ result.datasource.name }}
      <br />
      sample1: {{ result.datasource.sample1.value }}
      <br />
      sample1 (editable): <sc-text :field="result.datasource.sample1.jsonValue" />
      <br />
      sample2:<br />
      <ul>
        <li>text: {{ result.datasource.sample2.text }}</li>
        <li>url: {{ result.datasource.sample2.url }}</li>
        <li>target: {{ result.datasource.sample2.target }}</li>
        <li>editable: <sc-link :field="result.datasource.sample2.jsonValue" /></li>
        <li>field type: {{ result.datasource.sample2.definition.type }}</li>
        <li>field is shared?: {{ result.datasource.sample2.definition.shared.toString() }}</li>
      </ul>
    </div>
    <div v-if="!loading && result && result.contextItem">
      <h4>Route Item (via Connected GraphQL)</h4>
      id: {{ result.contextItem.id }}
      <br />
      page title: {{ result.contextItem.pageTitle.value }}
      <br />
      children:
      <ul>
        <li v-for="child in result.contextItem.children" :key="child.id">
          <router-link :to="child.url.path">{{ child.pageTitle.value }}</router-link
          >&nbsp; (editable title too! <sc-text :field="child.pageTitle.jsonValue" />)
        </li>
      </ul>
    </div>
  </div>
</template>

<script>
import { getCurrentInstance, defineComponent } from 'vue';
import { useQuery } from '@vue/apollo-composable/dist/useQuery';
import { ConnectedDemoQuery } from './GraphQL-ConnectedDemo.query.graphql';

import { Text, Link } from '@sitecore-jss/sitecore-jss-vue';

export default defineComponent({
  name: 'GraphQL-ConnectedDemo',
  props: {
    fields: {
      type: Object,
    },
    rendering: {
      type: Object,
    },
  },
  components: {
    ScText: Text,
    ScLink: Link,
  },
  setup(props) {
    const instance = getCurrentInstance();

    const variables = () => {
      const properties = instance.appContext.config.globalProperties.$jss;
      const defaultValue = '{00000000-0000-0000-0000-000000000000}';
      const variables = {
        contextItem: properties ? properties.sitecoreContext().itemId : defaultValue,
        datasource: (props.rendering && props.rendering.dataSource) || defaultValue,
      };

      if (!variables.contextItem) variables.contextItem = defaultValue;

      return variables;
    };

    const { result, loading, error } = useQuery(ConnectedDemoQuery, variables());

    return {
      result,
      loading,
      error,
    };
  },
});
</script>

// samples/nextjs/src/components/GraphQL-ConnectedDemo/index.tsx
import { Text, Link } from '@sitecore-jss/sitecore-jss-nextjs';
import RouterLink from 'next/link';
import {
  ConnectedDemoQueryDocument,
  AppRoute,
  Item,
  GraphQlConnectedDemo as GrapQLConnectedDemoDatasource,
} from './query.graphql';
import initializeApollo from 'lib/GraphQLClientFactory';
import config from 'temp/config';
import {
  GetServerSideComponentProps,
  GetStaticComponentProps,
  StyleguideComponentProps,
  useComponentProps,
} from 'lib/component-props';

type RouteItem = AppRoute & Item;

type GraphQLConnectedDemoData = {
  datasource: GrapQLConnectedDemoDatasource;
  contextItem: RouteItem;
};

const GraphQLConnectedDemo = (props: StyleguideComponentProps): JSX.Element => {
  const data = useComponentProps<GraphQLConnectedDemoData>(props.rendering.componentName);

  const { datasource, contextItem } = data;

  return (
    <div data-e2e-id="graphql-connected">
      <h2>GraphQL Connected Demo</h2>

      <p>
        Connected GraphQL executes GraphQL queries directly against the Sitecore GraphQL endpoint.
        You can review the query execution in the browser devtools network tab. Note that Apollo
        Client maintains a query cache - so the same query will not execute twice (i.e. after route
        changes) unless either the page is refreshed, or the <em>fetch policy</em> is set to not use
        the cache. Consult the Apollo documentation for details.
      </p>

      {datasource && (
        <div>
          <h4>Datasource Item (via Connected GraphQL)</h4>
          id: {datasource.id}
          <br />
          name: {datasource.name}
          <br />
          sample1: {datasource.sample1?.value}
          <br />
          sample1 (editable): <Text field={datasource.sample1?.jss} />
          <br />
          sample2:
          <br />
          <ul>
            <li>text: {datasource.sample2?.text}</li>
            <li>url: {datasource.sample2?.url}</li>
            <li>target: {datasource.sample2?.target}</li>
            <li>
              editable: <Link field={datasource.sample2?.jss} />
            </li>
            <li>field type: {datasource.sample2?.definition?.type}</li>
            <li>field is shared?: {datasource.sample2?.definition?.shared.toString()}</li>
          </ul>
        </div>
      )}
      {contextItem && (
        <div>
          <h4>Route Item (via Connected GraphQL)</h4>
          id: {contextItem.id}
          <br />
          page title: {contextItem.pageTitle?.value}
          <br />
          children:
          <ul>
            {contextItem.children.map((child) => {
              const routeItem = child as RouteItem;

              return (
                <li key={routeItem.id}>
                  <RouterLink href={routeItem.url}>{routeItem.pageTitle?.value}</RouterLink>&nbsp;
                  (editable title too! <Text field={routeItem.pageTitle?.jss} />)
                </li>
              );
            })}
          </ul>
        </div>
      )}
    </div>
  );
};

/**
 * Will be called during SSG
 * @param rendering
 * @param layoutData
 * @param context
 */
export const getStaticProps: GetStaticComponentProps = async (rendering, layoutData) => {
  const apolloClient = initializeApollo({ endpoint: config.graphQLEndpoint });

  const result = await apolloClient.query({
    query: ConnectedDemoQueryDocument,
    variables: {
      datasource: rendering.dataSource,
      contextItem: layoutData?.sitecore.route.itemId,
    },
  });

  return result.data;
};

/**
 * Will be called during SSR
 * @param rendering
 * @param layoutData
 * @param context
 */
export const getServerSideProps: GetServerSideComponentProps = async (rendering, layoutData) => {
  const apolloClient = initializeApollo({ endpoint: config.graphQLEndpoint });

  const result = await apolloClient.query({
    query: ConnectedDemoQueryDocument,
    variables: {
      datasource: rendering.dataSource,
      contextItem: layoutData?.sitecore.route.itemId,
    },
  });

  return result.data;
};

export default GraphQLConnectedDemo;
