// samples/react-native/src/components/Styleguide-Layout-Tabs-Tab/index.js
import React from 'react';
import { View, Text as NText } from 'react-native'
import { RichText } from '@sitecore-jss/sitecore-jss-react-native';

/**
 * This is a single tab within the tabs sample component. These are added to the tabs placeholder.
 * This component demonstrates conditionally altering rendering when in the Sitecore Experience Editor to improve
 * author experience.
 */
const StyleguideLayoutTabsTab = ({ fields, rendering }) => (
  <View>
		<RichText field={fields.content} />
  </View>
);

export default StyleguideLayoutTabsTab;

// samples/nuxtjs/components/Styleguide/Styleguide-Layout-Tabs-Tab.vue
<!--
  This is a single tab within the tabs sample component. These are added to the tabs placeholder.
  This component demonstrates conditionally altering rendering when in the Sitecore Experience Editor to improve
  author experience.
-->
<template>
  <div data-e2e-class="styleguide-layout-tabs-tab">
    <sc-rich-text :field="fields.content" />
  </div>
</template>

<script>
import { RichText, Text } from '@sitecore-jss/sitecore-jss-vue';

export default {
  name: 'Styleguide-Layout-Tabs-Tab',
  props: {
    fields: {
      type: Object,
    },
    rendering: {
      type: Object,
    },
    params: {
      type: Object,
    },
  },
  components: {
    ScText: Text,
    ScRichText: RichText,
  },
};
</script>
