// samples/vue/src/components/Styleguide/Styleguide-Section.vue
<!--
  Represents a category of styleguide specimens within the Styleguide-Layout.
  Usage examples are added to the `styleguide-section` placeholder that this
  exposes.
-->
<template>
  <div class="pt-3" :id="`i${rendering.uid.replace(/[{}]/g, '')}`">
    <sc-text class="border-bottom" :field="fields.heading" tag="h3" />
    <sc-placeholder name="jss-styleguide-section" :rendering="rendering" />
  </div>
</template>

<script>
import { Placeholder, Text } from '@sitecore-jss/sitecore-jss-vue';

export default {
  name: 'Styleguide-Section',
  props: {
    rendering: {
      type: Object,
    },
    fields: {
      type: Object,
    },
  },
  components: {
    ScPlaceholder: Placeholder,
    ScText: Text,
  },
};
</script>

// samples/react/src/components/Styleguide-Section/index.js
import React from 'react';
import { Placeholder, Text } from '@sitecore-jss/sitecore-jss-react';

/**
 * Represents a category of styleguide specimens within the Styleguide-Layout.
 * Usage examples are added to the `styleguide-section` placeholder that this
 * exposes.
 */
const StyleguideSection = (props) => (
  <div className="pt-3" id={`i${props.rendering.uid.replace(/[{}]/g, '')}`}>
    <Text className="border-bottom" field={props.fields.heading} tag="h3" />
    <Placeholder name="jss-styleguide-section" rendering={props.rendering} />
  </div>
);

export default StyleguideSection;
