// packages/sitecore-jss-angular-forms/src/app/components/forms/fields/radio-button-list/radio-button-list.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { ValueFormField, ListViewModel, ListFieldItem, FormTracker } from '@sitecore-jss/sitecore-jss-forms';
import { FormStateService } from '../../services/form-state.service';

@Component({
  selector: 'app-radio-button-list',
  templateUrl: './radio-button-list.component.html',
  styleUrls: ['./radio-button-list.component.scss']
})
export class RadioButtonListComponent implements OnInit {
  field: ValueFormField<ListViewModel>;
  group: FormGroup;
  tracker: FormTracker;

  public items: ListFieldItem[];

  public constructor(private formState: FormStateService) { }

  public ngOnInit(): void { 
    this.items = this.field.model.items;
  }
  
  onChange($event): void {
    let valid = true;
    const errorMessages = [];

    // custom client validation logic here
    if (this.field.model.required && !$event.target.value) {
      valid = false;
      errorMessages.push(`${this.field.model.title} is required`);
    }

    this.formState.setFieldState(this.field.valueField.name, $event.target.value, valid, errorMessages);
  }

  onFocus($event): void {
    this.tracker.onFocusField(this.field, <string>this.field.model.value);
  }

  onBlur($event): void {
    this.tracker.onBlurField(this.field, <string>this.field.model.value);
  }
}

<app-label [title]="field.model.title" [class]="field.model.labelCssClass"></app-label>

<div aria-label="Select an option">
  <input *ngFor="let option of items; let idx = index;"
    type="radio"
    [ngClass]="field.model.cssClass" 
    [id]="field.valueField.id + idx" 
    [name]="field.valueField.name"
    [value]="option.value"
    [checked]="option.selected"
    (change)="onChange($event)"
    (focus)="onFocus($event)"
    (blur)="onBlur($event)" />{{option.text}}
</div>

// samples/react/src/components/Form/field-templates/radio-button-list.js
import React from 'react';
import FieldValidationErrors from './field-validation-errors';
import Label from './label';

function RadioButtonList({ field, value, isValid, errors, onChange }) {
  const items = field.model.items;

  // note: the value for list field types is an array (of selected values)

  return (
    <React.Fragment>
      <Label field={field} isValid={isValid} />
      {items.map((item, index) => (
        <label key={item.itemId}>
          <input
            type="radio"
            className={field.model.cssClass}
            id={field.valueField.id + index}
            name={field.valueField.name}
            value={item.value}
            checked={value.some((v) => v === item.value)}
            onChange={(e) => handleOnChange(field, e.target.value, onChange)}
          />
          {item.text}
        </label>
      ))}

      <FieldValidationErrors errors={errors} />
    </React.Fragment>
  );
}

function handleOnChange(field, newValue, callback) {
  let valid = true;
  const errorMessages = [];

  // custom client validation logic here
  if (field.model.required && !newValue) {
    valid = false;
    errorMessages.push(`${field.model.title} is required`);
  }

  callback(field.valueField.name, [newValue], valid, errorMessages);
}

export default RadioButtonList;
