// packages/create-sitecore-jss/src/templates/angular-sxp/src/app/components/styleguide-component-params/styleguide-component-params.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { ComponentRendering } from '@sitecore-jss/sitecore-jss-angular';

@Component({
  selector: 'app-styleguide-component-params',
  templateUrl: './styleguide-component-params.component.html',
})
export class StyleguideComponentParamsComponent implements OnInit {
  @Input() rendering: ComponentRendering;
  cssClass: string;
  useCta: string;
  useCtaType: string;
  columns: number;
  columnsArray: number[];

  constructor() { }

  ngOnInit() {
    this.cssClass = this.rendering.params.cssClass;
    this.useCta = this.rendering.params.useCallToAction;
    this.useCtaType = typeof this.rendering.params.useCallToAction;
    this.columns = parseInt(this.rendering.params.columns, 10);
    this.columnsArray = Array.from(Array(this.columns), (_, index) => index);
  }
}

<app-styleguide-specimen [rendering]="rendering" e2eId="styleguide-componentparams">
  <p class="{{ cssClass }}">
    The CSS class of this paragraph (<code>{{ cssClass }}</code>) is set using a param
  </p>
  <div>
    <!-- Note that all params come in as string values, like this boolean-like param here: -->
    useCallToAction param: <code>{{ useCta }}</code>
    <br />
    param type: <code>{{ useCtaType }}</code>
    <!-- because the param is a string, you need to compare it as a string - if(`useCta`) won't work correctly. -->
    @if (useCta === 'true') {
      <div class="alert alert-info">the call to action is shown</div>
    }
  </div>
  <p>columns param: {{ columns }}</p>
  <div class="row">
    @for (column of columnsArray; track column) {
      <div class="col-sm">
        Column {{ column }}
      </div>
    }
  </div>
</app-styleguide-specimen>

// samples/nextjs/src/components/Styleguide-ComponentParams/index.tsx
import StyleguideSpecimen from '../Styleguide-Specimen';
import { ComponentRendering, Field } from '@sitecore-jss/sitecore-jss-nextjs';

interface StyleguideComponentParamsProps {
  fields: {
    description: Field<string>;
    heading: Field<string>;
  };
  rendering: ComponentRendering;
  params: {
    cssClass: string;
    columns: string;
    useCallToAction: 'false' | 'true';
  };
}

const StyleguideComponentParams: React.FC<StyleguideComponentParamsProps> = (props) => {
  // props.params (i.e. props.params.cssClass without destructuring) contains the component's params
  const { cssClass, columns, useCallToAction } = props.params;

  const columnsArray = columns && [...Array(parseInt(columns))];

  return (
    <StyleguideSpecimen {...props} e2eId="styleguide-componentparams">
      <p className={cssClass}>
        The CSS class of this paragraph (<code>{cssClass}</code>) is set using a param
      </p>
      <div>
        {/* Note that all params come in as string values, like this boolean-like param here: */}
        useCallToAction param: <code>{useCallToAction}</code>
        <br />
        param type: <code>{typeof useCallToAction}</code>
        {useCallToAction === 'true' && (
          <div className="alert alert-info">the call to action is shown</div>
        )}
      </div>
      <p>columns param: {columns}</p>
      <div className="row">
        {columnsArray &&
          columnsArray.map((_, index) => (
            <div key={`col-${index}`} className="col-sm">
              Column {index}
            </div>
          ))}
      </div>
    </StyleguideSpecimen>
  );
};

export default StyleguideComponentParams;
