// samples/nextjs/src/components/Styleguide-SitecoreContext/index.tsx
import {
  ComponentRendering,
  Field,
  RouteData,
  withSitecoreContext,
} from '@sitecore-jss/sitecore-jss-nextjs';
import StyleguideSpecimen from '../Styleguide-Specimen';

interface StyleguideSitecoreContextProps {
  fields: {
    heading: Field<string>;
    description: Field<string>;
  };
  rendering: ComponentRendering;
  sitecoreContext: RouteData;
}

/**
 * Demonstrates gaining access to the route-level Sitecore Context from
 * within other components.
 */
const StyleguideSitecoreContext: React.FC<StyleguideSitecoreContextProps> = (props) => (
  <StyleguideSpecimen {...props} e2eId="styleguide-sitecore-context">
    <p>The current Sitecore Context is...</p>
    <pre style={{ maxHeight: '400px', overflow: 'scroll' }}>
      {JSON.stringify(props.sitecoreContext, null, 2)}
    </pre>
  </StyleguideSpecimen>
);

export default withSitecoreContext()(StyleguideSitecoreContext);

// samples/vue/src/components/Styleguide/Styleguide-SitecoreContext.vue
<!--
  Demonstrates gaining access to the route-level Sitecore Context from
  within other components.
-->
<template>
  <styleguide-specimen v-bind="$props">
    <p>The current Sitecore Context is...</p>
    <!--
      this.$jss is defined on the Vue instance by the SitecoreJssPlugin and provides
      reactive access to the `sitecoreContext` provided in layout service data.
    -->
    <pre :style="{maxHeight: '400px', overflow: 'scroll'}">
  {{ JSON.stringify($jss.sitecoreContext(), null, 2) }}
    </pre>
  </styleguide-specimen>
</template>

<script>
import StyleguideSpecimen from './Styleguide-Specimen';

export default {
  name: 'Styleguide-SitecoreContext',
  props: {
    fields: {
      type: Object,
    },
    rendering: {
      type: Object,
    },
  },
  components: {
    StyleguideSpecimen,
  },
};
</script>
