// samples/nextjs/src/components/Styleguide-Multilingual/index.tsx
import { Text, Field } from '@sitecore-jss/sitecore-jss-nextjs';
import Link from 'next/link';
import { useI18n } from 'next-localization';
import StyleguideSpecimen from 'components/Styleguide-Specimen';
import { StyleguideComponentWithContextProps, StyleguideSpecimenFields } from 'lib/component-props';

type StyleguideMultilingualProps = StyleguideComponentWithContextProps &
  StyleguideSpecimenFields & {
    fields: {
      sample: Field<string>;
    };
  };

/**
 * Demonstrates using the dictionary functionality and defining route data in
 * multiple languages.
 */
const StyleguideMultilingual = (props: StyleguideMultilingualProps): JSX.Element => {
  const i18n = useI18n();

  return (
    <StyleguideSpecimen {...props} e2eId="styleguide-multilingual">
      <Text field={props.fields.sample} encode={false} tag="p" />

      <p>
        This is a static dictionary entry from <code>/data/dictionary</code>
        :&nbsp;
        {i18n.t('styleguide-sample')}
      </p>

      <p>
        <Link href="/styleguide" locale="en">
          <a>Show in English</a>
        </Link>
        <br />
        <Link href="/styleguide" locale="da-DK">
          <a>Show in Danish</a>
        </Link>
      </p>

      <p>The current language is: {i18n.locale()}</p>
    </StyleguideSpecimen>
  );
};

export default StyleguideMultilingual;

// samples/vue/src/components/Styleguide/Styleguide-Multilingual.vue
<!--
  Demonstrates using the dictionary functionality and defining route data in
  multiple languages.
-->
<template>
  <styleguide-specimen v-bind="$props" data-e2e-id="styleguide-multilingual">
    <sc-text :field="fields.sample" :encode="false" tag="p" />

    <p>
      <!-- $t is attached to the Vue instance by the i18n plugin -->
      This is a static dictionary entry from <code>/data/dictionary</code>:&nbsp;{{
        $t('styleguide-sample')
      }}
    </p>

    <p>
      <router-link to="/en/styleguide">Show in English</router-link>
      <br />
      <router-link to="/da-DK/styleguide">Show in Danish</router-link>
    </p>

    <!-- $i18n is attached to the Vue instance by the i18n plugin -->
    <p>The current language is: {{ $i18n.locale }}</p>
  </styleguide-specimen>
</template>

<script>
import { Text } from '@sitecore-jss/sitecore-jss-vue';
import StyleguideSpecimen from './Styleguide-Specimen';

export default {
  name: 'Styleguide-Multilingual',
  props: {
    fields: {
      type: Object,
    },
    rendering: {
      type: Object,
    },
  },
  components: {
    StyleguideSpecimen,
    ScText: Text,
  },
};
</script>
