// samples/react/src/components/Styleguide-FieldUsage-Number/index.js
import React from 'react';
import { Text, getFieldValue } from '@sitecore-jss/sitecore-jss-react';
import StyleguideSpecimen from '../Styleguide-Specimen';

/**
 * Demonstrates usage of a Number (decimal) content field within JSS.
 */
const StyleguideFieldUsageText = (props) => {
  const fieldValue = getFieldValue(props.fields, 'sample');

  return (
    <StyleguideSpecimen {...props}>
      {/* Basic emission of a number field for editing can be done with the <Text> component. */}
      <Text field={props.fields.sample} />

      {/* Direct access to the value, which is a JS number, is also supported. */}
      <p>
        JS value type: {typeof fieldValue}
        <br />
        JS value: {fieldValue}
      </p>
    </StyleguideSpecimen>
  );
};

export default StyleguideFieldUsageText;

// samples/vue/src/components/Styleguide/Styleguide-FieldUsage-Number.vue
<!--
  Demonstrates usage of a Number (decimal) content field within JSS.
-->
<template>
  <styleguide-specimen v-bind="$props">
    <!-- Basic emission of a number field for editing can be done with the <Text> component. -->
      <sc-text :field="fields.sample" />

      <!-- Direct access to the value, which is a JS number, is also supported. -->
      <p>
        JS value type: {{ typeof fieldValue }}
        <br />
        JS value: {{ fieldValue }}
      </p>
  </styleguide-specimen>
</template>

<script>
import { Text, getFieldValue } from '@sitecore-jss/sitecore-jss-vue';
import StyleguideSpecimen from './Styleguide-Specimen';

export default {
  name: 'Styleguide-FieldUsage-Number',
  props: {
    fields: {
      type: Object,
    },
    rendering: {
      type: Object,
    },
  },
  components: {
    ScText: Text,
    StyleguideSpecimen,
  },
  computed: {
    fieldValue() {
      return getFieldValue(this.fields, 'sample');
    },
  },
};
</script>
