// samples/react/src/components/Styleguide-ComponentParams/index.js
import React from 'react';
import StyleguideSpecimen from '../Styleguide-Specimen';

const StyleguideComponentParams = (props) => {
  // props.params (i.e. props.params.cssClass without destructuring) contains the component's params
  const { cssClass, columns, useCallToAction } = props.params;

  const columnsArray = columns && [...Array(parseInt(columns))];

  return (
    <StyleguideSpecimen {...props}>
      <p className={cssClass}>
        The CSS class of this paragraph (<code>{cssClass}</code>) is set using a param
      </p>
      <div>
        {/* Note that all params come in as string values, like this boolean-like param here: */}
        useCallToAction param: <code>{useCallToAction}</code>
        <br />
        param type: <code>{typeof useCallToAction}</code>
        {useCallToAction === 'true' && (
          <div className="alert alert-info">the call to action is shown</div>
        )}
      </div>
      <p>columns param: {columns}</p>
      <div className="row">
        {columnsArray &&
          columnsArray.map((_, index) => (
            <div key={`col-${index}`} className="col-sm">
              Column {index}
            </div>
          ))}
      </div>
    </StyleguideSpecimen>
  );
};

export default StyleguideComponentParams;

// samples/vue/src/components/Styleguide/Styleguide-ComponentParams.vue
<template>
  <styleguide-specimen v-bind="$props">
    <p :class="params.cssClass">
      The CSS class of this paragraph (<code>{{ params.cssClass }}</code>) is set using a param
    </p>
    <div>
      <!-- Note that all params come in as string values, like this boolean-like param here: -->
      useCallToAction param: <code>{{ params.useCallToAction }}</code>
      <br />
      param type: <code>{{ typeof params.useCallToAction }}</code>
      <div class="alert alert-info" v-if="params.useCallToAction === 'true'">the call to action is shown</div>
    </div>
    <p>columns param: {{ params.columns }}</p>
    <div class="row" v-if="columnsArray">
      <div v-for="(_, index) in columnsArray" :key="index" class="col-sm">
        Column {{index}}
      </div>
    </div>
  </styleguide-specimen>
</template>

<script>
import StyleguideSpecimen from './Styleguide-Specimen';
export default {
  name: 'Styleguide-Specimen',
  props: {
    params: {
      type: Object,
    },
    fields: {
      type: Object,
    },
    rendering: {
      type: Object,
    },
  },
  computed: {
    columnsArray() {
      return this.params.columns && [...Array(parseInt(this.params.columns))];
    },
  },
  components: {
    StyleguideSpecimen,
  },
};
</script>
