// samples/react-native/src/components/Styleguide-FieldUsage-Custom/index.js
import React from 'react';
import { Text } from '@sitecore-jss/sitecore-jss-react-native';
import StyleguideSpecimen from '../Styleguide-Specimen/Styleguide-Specimen';

/**
 * Demonstrates usage of a custom content field type within JSS.
 * See /sitecore/definitions/components/Styleguide-FieldUsage-Custom.sitecore.js
 * for the definition of the structure of the custom field. This code is just for display.
 */
const StyleguideFieldUsageCustom = ({ fields, rendering }) => (
	<StyleguideSpecimen fields={fields} rendering={rendering}>
		{/* Because the integer field is essentially text, we can render it with the Text helper */}
		<Text field={fields.customIntField} />
	</StyleguideSpecimen>
);

export default StyleguideFieldUsageCustom;

// samples/vue/src/components/Styleguide/Styleguide-FieldUsage-Custom.vue
<!--
  Demonstrates usage of a custom content field type within JSS.
  See /sitecore/definitions/components/Styleguide-FieldUsage-Custom.sitecore.js
  for the definition of the structure of the custom field. This code is just for display.
-->
<template>
  <styleguide-specimen v-bind="$props">
    <!-- Because the integer field is essentially text, we can render it with the Text helper -->
    <sc-text :field="fields.customIntField" />
  </styleguide-specimen>
</template>

<script>
import { Text } from '@sitecore-jss/sitecore-jss-vue';
import StyleguideSpecimen from './Styleguide-Specimen';

export default {
  name: 'Styleguide-FieldUsage-Custom',
  props: {
    fields: {
      type: Object,
    },
    rendering: {
      type: Object,
    },
  },
  components: {
    ScText: Text,
    StyleguideSpecimen,
  },
};
</script>
