// packages/create-sitecore-jss/src/templates/vue/src/Layout.vue
<template>
  <metainfo>
    <template v-slot:title="{ content }">{{ content }}</template>
  </metainfo>
  <div>
    <visitor-identification />
    <navigation />
    <div class="container">
      <placeholder name="<%- helper.getAppPrefix(appPrefix, appName) %>jss-main" :rendering="route" />
    </div>
  </div>
</template>

<script>
import { defineComponent } from 'vue';
import { Placeholder } from '@sitecore-jss/sitecore-jss-vue';
import Navigation from './Navigation';
import VisitorIdentification from './VisitorIdentification';
import { useMeta } from 'vue-meta';
import 'bootstrap/dist/css/bootstrap.css';
import './assets/app.css';

export default defineComponent({
  name: 'Layout',
  props: {
    route: {
      type: Object,
      default: () => ({}),
    },
  },
  setup(props) {
    useMeta({
      title:
        (props.route.fields &&
          props.route.fields.pageTitle &&
          props.route.fields.pageTitle.value) ||
        'Page',
    });
  },
  components: {
    Placeholder,
    Navigation,
    VisitorIdentification,
  },
});
</script>

// packages/create-sitecore-jss/src/templates/nextjs-personalize/src/Layout.tsx
import React from 'react';
import Head from 'next/head';
import {
  Placeholder,
  VisitorIdentification,
  getPublicUrl,
  LayoutServiceData,
} from '@sitecore-jss/sitecore-jss-nextjs';
import Navigation from 'src/Navigation';
import CdpIntegrationScript from 'components/CdpIntegrationScript';

// Prefix public assets with a public URL to enable compatibility with Sitecore Experience Editor.
// If you're not supporting the Experience Editor, you can remove this.
const publicUrl = getPublicUrl();

interface LayoutProps {
  layoutData: LayoutServiceData;
}

const Layout = ({ layoutData }: LayoutProps): JSX.Element => {
  const { route } = layoutData.sitecore;

  return (
    <>
      {route && (
        <CdpIntegrationScript />
      )}
      <Head>
        <title>{route?.fields?.pageTitle?.value || 'Page'}</title>
        <link rel="icon" href={`${publicUrl}/favicon.ico`} />
      </Head>

      {/*
        VisitorIdentification is necessary for Sitecore Analytics to determine if the visitor is a robot.
        If Sitecore XP (with xConnect/xDB) is used, this is required or else analytics will not be collected for the JSS app.
        For XM (CMS-only) apps, this should be removed.

        VI detection only runs once for a given analytics ID, so this is not a recurring operation once cookies are established.
      */}
      <VisitorIdentification />

      <Navigation />
      {/* root placeholder for the app, which we add components to using route data */}
      <div className="container">
        {route && <Placeholder name="<%- helper.getAppPrefix(appPrefix, appName) %>jss-main" rendering={route} />}
      </div>
    </>
  );
};

export default Layout;
