// packages/sitecore-jss-react-forms/src/components/field-templates/section.tsx
import React from 'react';
import { FieldProps } from '../../FieldProps';
import { FormFieldSection } from '@sitecore-jss/sitecore-jss-forms';

const Section: React.FunctionComponent<FieldProps<FormFieldSection>> = ({
  field,
  fieldFactory,
}) => (
  <fieldset className={field.model.cssClass}>
    {field.fields.map(fieldFactory)}
  </fieldset>
);

export default Section;

// packages/sitecore-jss-angular-forms/src/app/components/forms/fields/section/section.component.ts
import { Component, OnInit } from '@angular/core';
import { FormFieldSection, FormField } from '@sitecore-jss/sitecore-jss-forms';
import { FormGroup } from '@angular/forms';

@Component({
  selector: 'app-section',
  templateUrl: './section.component.html'
})
export class SectionComponent implements OnInit {
  field: FormFieldSection;
  fields: FormField[];
  group: FormGroup;

  public constructor() { }

  public ngOnInit(): void { 
    this.fields = this.field.fields;
  }
}

<div [ngClass]="field.model.cssClass">
  <ng-container *ngFor="let field of fields;" dynamicField [field]="field" [group]="group"></ng-container>
</div>
