// samples/basic-sample-vue-web/src/app/components/Welcome.vue
<template>
  <div id="CenterColumn">
    <div id="InnerCenter">
      <div id="Header">
        <sc-image :media="fields.logoImage" id="scLogo" />
      </div>
      <div id="Content">
        <div id="LeftContent">
          <sc-text tag="h1" :field="fields.title" class="contentTitle" />
          <sc-rich-text class="contentDescription" :field="fields.text" />
        </div>
      </div>
      <div id="Footer">
        <hr class="divider" />
        {{ copyright }}
      </div>
    </div>
  </div>
</template>

<script>
import { Image, Text, RichText } from '@sitecore-jss/sitecore-jss-vue';

export default {
  name: 'Welcome',
  props: {
    fields: {
      type: Object,
      default: () => ({}),
    },
    copyright: {
      type: String,
      default: 'Copyright Sitecore A/S',
    },
  },
  components: {
    ScImage: Image,
    ScText: Text,
    ScRichText: RichText,
  },
};
</script>

<style>

</style>

// samples/basic-sample-angular/src/app/components/welcome/welcome.component.ts
import { Component, Inject } from '@angular/core';
import { RENDERING_PROPERTIES } from '@sitecore-jss/sitecore-jss-angular';

@Component({
  selector: 'app-welcome',
  templateUrl: './welcome.component.html',
  styleUrls: ['./welcome.component.css']
})
export class WelcomeComponent {
  copyright = 'Copyright Sitecore A/S';

  constructor(
    @Inject(RENDERING_PROPERTIES) public props: any
  ) {}
}

<div id="CenterColumn">
  <div id="InnerCenter">
    <div id="Header">
      <img *scImage="props.fields.logoImage" />
    </div>
    <div id="Content">
      <div id="LeftContent">
        <h1 class="contentTitle" *scText="props.fields.title"></h1>
        <div class="contentDescription" *scRichText="props.fields.text"></div>
      </div>
    </div>
    <div id="Footer">
      <hr class="divider" />
      {{copyright}}
    </div>
  </div>
</div>
