// packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Title.tsx
import React from 'react';
import { Link, Text, useSitecoreContext, LinkField, TextField } from '@sitecore-jss/sitecore-jss-nextjs';

interface Fields {
  data: {
    datasource: {
      url: {
        path: string;
        siteName: string;
      };
      field: {
        jsonValue: {
          value: string;
          editable: string;
        };
      };
    };
    contextItem: {
      url: {
        path: string;
        siteName: string;
      };
      field: {
        jsonValue: {
          value: string;
          editable: string;
        };
      };
    };
  };
}

type TitleProps = {
  params: { [key: string]: string };
  fields: Fields;
};

type ComponentContentProps = {
  styles: string;
  children: JSX.Element;
};

const ComponentContent = (props: ComponentContentProps) => {
  return (
    <div className={`component title ${props.styles}`}>
      <div className="component-content">
        <div className="field-title">{props.children}</div>
      </div>
    </div>
  );
};

export const Default = (props: TitleProps): JSX.Element => {
  const datasource = props.fields?.data?.datasource || props.fields?.data?.contextItem;
  const text: TextField = {
    value: datasource?.field?.jsonValue?.value,
    editable: datasource?.field?.jsonValue?.editable,
  };
  const link: LinkField = {
    value: {
      href: datasource?.url?.path,
      title: datasource?.field?.jsonValue?.value,
      editable: true,
    },
  };
  if (useSitecoreContext().sitecoreContext.pageState !== 'normal') {
    link.value.querystring = `sc_site=${datasource?.url?.siteName}`;
    if (!text.value) {
      text.value = 'Title field';
      link.value.href = '#';
    }
  }

  return (
    <ComponentContent styles={props.params.styles}>
      <Link field={link}>
        <Text field={text} />
      </Link>
    </ComponentContent>
  );
};

// packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/title/title.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { LinkField, SxaTitleFields, TextField } from '@sitecore-jss/sitecore-jss-angular';
import { SxaComponent } from '../sxa.component';
import { Subscription } from 'rxjs';
import { JssContextService } from '../../jss-context.service';

@Component({
  selector: 'app-title',
  templateUrl: './title.component.html',
})
export class TitleComponent extends SxaComponent<SxaTitleFields> implements OnInit, OnDestroy {
  text: TextField;
  link: LinkField;
  pageEditing?: boolean;
  
  private contextSubscription: Subscription;

  constructor(private jssContext: JssContextService) {
    super();
  }

  ngOnInit() {
    super.ngOnInit();
    const datasource =
      this.rendering.fields?.data?.datasource || this.rendering.fields?.data?.contextItem;
    this.text = datasource.field?.jsonValue;
    this.link = {
      value: {
        href: datasource?.url?.path,
        title: datasource?.field?.jsonValue?.value,
      },
    };
    this.contextSubscription = this.jssContext.state.subscribe(({ sitecore }) => {
      this.pageEditing = sitecore.context.pageEditing;
      if (sitecore.context.pageState !== 'normal') {
        this.link.value.querystring = `sc_site=${datasource?.url?.siteName}`;
        if (!this.text?.value) {
          this.text.value = 'Title field';
          this.link.value.href = '#';
        }
      }
    });
  }

  ngOnDestroy() {
    if (this.contextSubscription) {
      this.contextSubscription.unsubscribe();
    }
  }
}

<div class="component title {{ styles }}" [attr.id]="id">
  <div clas="component-content">
    <div class="field-title">
      <ng-container *ngIf="!pageEditing; else textOnly">
        <a *scLink="link">
          <ng-content *scText="text"></ng-content>
        </a>
      </ng-container>
    </div>
  </div>
  <ng-template #textOnly>
    <ng-content [scText]="text"></ng-content>
  </ng-template>
</div>
