// packages/create-sitecore-jss/src/templates/vue/src/Navigation.vue
<template>
  <div
    class="
      d-flex
      flex-column flex-md-row
      align-items-center
      p-3
      px-md-4
      mb-3
      bg-white
      border-bottom
    "
  >
    <h5 class="my-0 me-md-auto fw-normal">
      <router-link to="/" class="text-dark">
        <img :src="logoImg" alt="Sitecore" />
      </router-link>
    </h5>
    <!-- note: `$t` is a computed property on the Vue instance, defined by the vue-i18n plugin -->
    <nav class="my-2 my-md-0 me-md-3">
      <a
        class="p-2 text-dark"
        href="https://jss.sitecore.com"
        target="_blank"
        rel="noopener noreferrer"
      >
        {{ $t('Documentation') }}
      </a>
      <router-link to="/styleguide" class="p-2 text-dark">
        {{ $t('Styleguide') }}
      </router-link>
      <router-link to="/graphql" class="p-2 text-dark">
        {{ $t('GraphQL') }}
      </router-link>
      <button class="btn btn-secondary align-baseline" type="button" v-on:click="toggleContext">
        {{ contextButtonText }}
      </button>
    </nav>
  </div>
</template>

<script>
import logo from './assets/sc_logo.svg';

export default {
  name: 'Navigation',
  data() {
    return {
      contextButtonText: '',
      logoImg: logo,
    };
  },
  created() {
    // $t is a computed property, so it's not defined when initializing the `data` object.
    // Therefore, use the `created` hook to set the data.
    this.contextButtonText = this.$t('show-context-data');
  },
  // `toggleContextView` is provided from AppRoot
  inject: {
    toggleContextView: {
      type: Function,
    },
  },
  methods: {
    toggleContext() {
      this.toggleContextView();
      this.contextButtonText =
        this.contextButtonText === this.$t('hide-context-data')
          ? this.$t('show-context-data')
          : this.$t('hide-context-data');
    },
  },
};
</script>

// packages/create-sitecore-jss/src/templates/nextjs-styleguide-tracking/src/Navigation.tsx
import Link from 'next/link';
import { useI18n } from 'next-localization';

const Navigation = (): JSX.Element => {
  const { t } = useI18n();

  return (
    <div className="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom">
      <h5 className="my-0 me-md-auto fw-normal">
        <Link className="text-dark" href="/">
          <img src={`/sc_logo.svg`} alt="Sitecore" />
        </Link>
      </h5>
      <nav className="my-2 my-md-0 me-md-3">
        <a
          className="p-2 text-dark"
          href="https://jss.sitecore.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          {t('Documentation')}
        </a>
        <Link className="p-2 text-dark" href="/styleguide">
          {t('Styleguide')}
        </Link>
        <Link className="p-2 text-dark" href="/graphql">
          {t('GraphQL')}
        </Link>
        <Link className="p-2 text-dark" href="/tracking">
          {t('Tracking')}
        </Link>
      </nav>
    </div>
  );
};

export default Navigation;
