// packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/Promo.tsx
import React from 'react';
import {
  Image as JssImage,
  Link as JssLink,
  RichText as JssRichText,
  ImageField,
  Field,
  LinkField,
  Text,
} from '@sitecore-jss/sitecore-jss-nextjs';

interface Fields {
  PromoIcon: ImageField;
  PromoText: Field<string>;
  PromoLink: LinkField;
  PromoText2: Field<string>;
}

type PromoProps = {
  params: { [key: string]: string };
  fields: Fields;
};

const PromoDefaultComponent = (props: PromoProps): JSX.Element => (
  <div className={`component promo ${props.params.styles}`}>
    <div className="component-content">
      <span className="is-empty-hint">Promo</span>
    </div>
  </div>
);

export const Default = (props: PromoProps): JSX.Element => {
  const id = props.params.RenderingIdentifier;
  if (props.fields) {
    return (
      <div className={`component promo ${props.params.styles}`} id={id ? id : undefined}>
        <div className="component-content">
          <div className="field-promoicon">
            <JssImage field={props.fields.PromoIcon} />
          </div>
          <div className="promo-text">
            <div>
              <div className="field-promotext">
                <JssRichText field={props.fields.PromoText} />
              </div>
            </div>
            <div className="field-promolink">
              <JssLink field={props.fields.PromoLink} />
            </div>
          </div>
        </div>
      </div>
    );
  }

  return <PromoDefaultComponent {...props} />;
};

export const WithText = (props: PromoProps): JSX.Element => {
  const id = props.params.RenderingIdentifier;
  if (props.fields) {
    return (
      <div className={`component promo ${props.params.styles}`} id={id ? id : undefined}>
        <div className="component-content">
          <div className="field-promoicon">
            <JssImage field={props.fields.PromoIcon} />
          </div>
          <div className="promo-text">
            <div>
              <div className="field-promotext">
                <Text className="promo-text" field={props.fields.PromoText} />
              </div>
            </div>
            <div className="field-promotext">
              <Text className="promo-text" field={props.fields.PromoText2} />
            </div>
          </div>
        </div>
      </div>
    );
  }

  return <PromoDefaultComponent {...props} />;
};

// packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/promo/promo.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { JssModule } from '@sitecore-jss/sitecore-jss-angular';
import { SxaComponent } from '../sxa.component';

@Component({
  selector: 'app-promo',
  templateUrl: './promo.component.html',
  imports: [CommonModule, JssModule],
  host: {
    'class': 'component promo',
    '[class]': "styles",
    '[id]': "id",
  },
})
export class PromoComponent extends SxaComponent {}

<div class="component promo {{ styles }}"  [attr.id]="id">
  <div class="component-content">
    <ng-container *ngIf="!empty; else emptyPromo">
      <div class="field-promoicon">
        <img *scImage="rendering.fields.PromoIcon"/>
      </div>
      <div class="promo-text">
        <div>
          <div class="field-promotext">
            <div class="{{ withText ? 'promo-text': undefined }}" *scRichText="rendering.fields.PromoText"></div>
          </div>
        </div>
        <div *ngIf="withText; else jssLink" class="field-promotext">
          <div class="promo-text" *scRichText="rendering.fields.PromoText2"></div>
        </div>
      </div>
    </ng-container>    
  </div>
  <ng-template #emptyPromo>
    <span class="is-empty-hint">Promo</span>
  </ng-template>
  <ng-template #jssLink>
    <div class="field-promolink">
      <a *scLink="rendering.fields.PromoLink"></a>
    </div>
  </ng-template>
</div>
