// samples/react/src/components/Form/field-templates/list-box.js
import React from 'react';
import FieldValidationErrors from './field-validation-errors';
import Label from './label';

function ListBox({ field, value, isValid, errors, onChange }) {
  const items = field.model.items;
  let finalValue = value;

  // react does not like an array as a value unless multiple select is allowed
  // (even if the array is always length 1)
  if (!field.model.multipleSelection) {
    finalValue = value[0];
  }

  // note: the value for list field types is an array (of selected values)
  // dropdown is single-select so we use value[0] for its value

  return (
    <React.Fragment>
      <Label field={field} isValid={isValid} />
      <select
        className={field.model.cssClass}
        id={field.valueField.id}
        name={field.valueField.name}
        value={finalValue}
        size={field.model.rows}
        multiple={field.model.multipleSelection}
        onChange={(e) => handleOnChange(field, e.target.options, onChange)}
      >
        {items.map((item) => (
          <option key={item.itemId} value={item.value}>
            {item.text}
          </option>
        ))}
      </select>

      <FieldValidationErrors errors={errors} />
    </React.Fragment>
  );
}

function handleOnChange(field, options, callback) {
  let valid = true;
  const errorMessages = [];

  const newValues = [];

  for (let i = 0; i < options.length; i += 1) {
    if (options[i].selected) {
      newValues.push(options[i].value);
    }
  }

  // custom client validation logic here
  if (field.model.required && newValues.length === 0) {
    valid = false;
    errorMessages.push(`${field.model.title} is required`);
  }

  callback(field.valueField.name, newValues, valid, errorMessages);
}

export default ListBox;

// packages/sitecore-jss-angular-forms/src/app/components/forms/fields/list-box/list-box.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { ValueFormField, ListBoxViewModel, ListFieldItem, FormTracker } from '@sitecore-jss/sitecore-jss-forms';
import { FormStateService } from '../../services/form-state.service';

@Component({
  selector: 'app-list-box',
  templateUrl: './list-box.component.html',
  styleUrls: ['./list-box.component.scss']
})
export class ListBoxComponent implements OnInit {
  field: ValueFormField<ListBoxViewModel>;
  group: FormGroup;
  tracker: FormTracker;

  public items: ListFieldItem[];

  public constructor(private formState: FormStateService) { }

  public ngOnInit(): void { 
    this.items = this.field.model.items;
  }
 
  onChange($event): void {
    let valid = true;
    let options = $event.target.options;

    const errorMessages = [];
    const newValues = [];

    for (let i = 0; i < options.length; i += 1) {
      if (options[i].selected) {
        newValues.push(options[i].value);
      }
    }

    // custom client validation logic here
    if (this.field.model.required && newValues.length === 0) {
      valid = false;
      errorMessages.push(`${this.field.model.title} is required`);
    }

    this.formState.setFieldState(this.field.valueField.name, newValues, valid, errorMessages);
  }

  onFocus($event): void {
    this.tracker.onFocusField(this.field, <string>this.field.model.value);
  }

  onBlur($event): void {
    this.tracker.onBlurField(this.field, <string>this.field.model.value);
  }
}

<app-label [title]="field.model.title" [class]="field.model.labelCssClass"></app-label>
<select
  [ngClass]="field.model.cssClass" 
  [id]="field.valueField.id" 
  [name]="field.valueField.name"
  [value]="field.model.value"
  [size]="field.model.rows"
  [multiple]="field.model.multipleSelection"
  (change)="onChange($event)"
  (focus)="onFocus($event)"
  (blur)="onBlur($event)">
  <option *ngFor="let option of items;" [value]="option.value">
    {{option.text}}
  </option>
</select>
