// packages/sitecore-jss-angular-forms/src/app/components/forms/fields/checkbox/checkbox.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { ValueFormField, FormTracker } from '@sitecore-jss/sitecore-jss-forms';
import { FormStateService } from '../../services/form-state.service';

@Component({
  selector: 'app-checkbox',
  templateUrl: './checkbox.component.html'
})
export class CheckboxComponent implements OnInit {
  field: ValueFormField;
  group: FormGroup;
  tracker: FormTracker

  public constructor(private formState: FormStateService) { }

  public ngOnInit(): void { }

  onChange($event): void {
    let valid = true;
    const errorMessages = [];

    // custom client validation logic here
    if (this.field.model.required && !$event.target.checked) {
      valid = false;
      errorMessages.push(`${this.field.model.title} is required`);
    }

    this.formState.setFieldState(this.field.valueField.name, $event.target.value, valid, errorMessages);
  }

  onFocus($event): void {
    this.tracker.onFocusField(this.field, $event.target.value);
  }

  onBlur($event): void {
    this.tracker.onBlurField(this.field, $event.target.value);
  }
}

<input
  type="checkbox"
  [ngClass]="field.model.cssClass" 
  [id]="field.valueField.id" 
  [name]="field.valueField.name"
  [checked]="field.model.value"
  (change)="onChange($event)"
  (focus)="onFocus($event)"
  (blur)="onBlur($event)" />
<app-label [title]="field.model.title" [class]="field.model.labelCssClass"></app-label>

<!-- <ng-container *ngFor="let validation of field.validations;" ngProjectAs="mat-error">
  <mat-error *ngIf="group.get(field.name).hasError(validation.name)">{{validation.message}}</mat-error>
</ng-container> -->

// packages/sitecore-jss-react-forms/src/components/field-templates/checkbox.tsx
import React, { Fragment } from 'react';
import { FieldValidationErrors } from './field-validation-errors';
import { Label } from './label';
import { ValueFieldProps, FieldChangeCallback } from '../../FieldProps';
import { ValueFormField } from '@sitecore-jss/sitecore-jss-forms';

const Checkbox: React.FunctionComponent<ValueFieldProps> = (props) => {
  const { field, value, onChange, tracker, errors } = props;
  return (
    <Fragment>
      <Label {...props}>
        <input
          type="checkbox"
          className={field.model.cssClass}
          id={field.valueField.id}
          name={field.valueField.name}
          value="true"
          checked={(value as unknown) as boolean}
          onChange={(e) => handleOnChange(field, e.target.checked, onChange)}
          onFocus={() => tracker.onFocusField(field, value)}
          onBlur={() => tracker.onBlurField(field, value, errors)}
        />
      </Label>
      <FieldValidationErrors {...props} />
    </Fragment>
  );
};

function handleOnChange(field: ValueFormField, fieldValue: boolean, callback: FieldChangeCallback) {
  // (fieldName, fieldValue, isValid, validationErrors)
  callback(field.valueField.name, fieldValue as any, true, []);
}

export default Checkbox;
