// packages/sitecore-jss-angular-forms/src/app/components/forms/fields/date/date.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { ValueFormField, DateInputViewModel, FormTracker } from '@sitecore-jss/sitecore-jss-forms';
import { FormStateService } from '../../services/form-state.service';

@Component({
  selector: 'app-date',
  templateUrl: './date.component.html'
})
export class DateComponent implements OnInit {
  field: ValueFormField<DateInputViewModel>;
  group: FormGroup;
  tracker: FormTracker;

  public constructor(private formState: FormStateService) { }

  public ngOnInit(): void { }

  public formatDateValue(value: string): string {
    if (!value || value.length < 10) {
      return value;
    }
    return value.substring(0, 10);
  }

  onChange($event): void {
    let valid = true;
    const errorMessages = [];

    // custom client validation logic here
    if (this.field.model.required && !$event.target.value) {
      valid = false;
      errorMessages.push(`${this.field.model.title} is required`);
    }

    this.formState.setFieldState(this.field.valueField.name, $event.target.value, valid, errorMessages);
  }

  onFocus($event): void {
    this.tracker.onFocusField(this.field, $event.target.value);
  }

  onBlur($event): void {
    this.tracker.onBlurField(this.field, $event.target.value);
  }
}

<app-label [title]="field.model.title" [class]="field.model.labelCssClass"></app-label>
<input 
  type="date"
  [ngClass]="field.model.cssClass" 
  [id]="field.valueField.id" 
  [name]="field.valueField.name" 
  [value]="field.model.value"
  [min]="field.model.min"
  [max]="field.model.max"
  (change)="onChange($event)"
  (focus)="onFocus($event)"
  (blur)="onBlur($event)" />

<!-- <ng-container *ngFor="let validation of field.validations;" ngProjectAs="mat-error">
  <mat-error *ngIf="group.get(field.name).hasError(validation.name)">{{validation.message}}</mat-error>
</ng-container> -->

// packages/sitecore-jss-react-forms/src/components/field-templates/date.tsx
import React, { Fragment } from 'react';
import { FieldValidationErrors } from './field-validation-errors';
import { Label } from './label';
import { ValueFieldProps, FieldChangeCallback } from '../../FieldProps';
import { DateInputViewModel, ValueFormField } from '@sitecore-jss/sitecore-jss-forms';

const DateField: React.FunctionComponent<ValueFieldProps<DateInputViewModel>> = (props) => {
  const { field, value, onChange, tracker, errors } = props;

  return (
    <Fragment>
      <Label {...props} />
      <input
        type="date"
        className={field.model.cssClass}
        id={field.valueField.id}
        name={field.valueField.name}
        value={formatValue(value)}
        min={formatValue(field.model.min)}
        max={formatValue(field.model.max)}
        onChange={(e) => handleOnChange(field, e.target.value, onChange)}
        onFocus={() => tracker.onFocusField(field, value)}
        onBlur={() => tracker.onBlurField(field, value, errors)}
      />
      <FieldValidationErrors {...props} />
    </Fragment>
  );
};

function formatValue(value?: string) {
  // dates are serialized from the API as full date/times (i.e. 2019-01-11T00:00:00)
  // but the date input expects only the date. Since the format is predictably long,
  // we can just take a substring.

  if (!value || value.length < 10) {
    return value;
  }
  return value.substring(0, 10);
}

function handleOnChange(field: ValueFormField, fieldValue: string, callback: FieldChangeCallback) {
  let valid = true;
  const errorMessages = [];

  // custom client validation logic here
  if (field.model.required && !fieldValue) {
    valid = false;
    errorMessages.push(`${field.model.title} is required`);
  }

  callback(field.valueField.name, fieldValue, valid, errorMessages);
}

export default DateField;
