// samples/angular/src/app/components/styleguide-field-usage-date/styleguide-field-usage-date.component.ts
import { Component, Input } from '@angular/core';
import { ComponentRendering } from '@sitecore-jss/sitecore-jss-angular';

/**
 * Demonstrates usage of date and time content field types within JSS.
 * NOTE: Usage of the *scDate directive is necessary to enable inline editing
 * of the date values in the Sitecore Experience Editor. The date value (as an ISO string)
 * is still available using the `getFieldValue()` helper if the raw value is needed.
 */
@Component({
  selector: 'app-styleguide-field-usage-date',
  templateUrl: './styleguide-field-usage-date.component.html',
})
export class StyleguideFieldUsageDateComponent {
  @Input() rendering: ComponentRendering;
}

<app-styleguide-specimen [rendering]="rendering">
  <ul>
    <li>
      Date directive (date field): <span *scDate="rendering.fields.date"></span>
    </li>
    <li>
      Date directive (dateTime field): <span *scDate="rendering.fields.dateTime"></span>
    </li>
    <li>
      <!--
        IMPORTANT: When editing the date in Experience Editor, the format, timezone, and locale options are ignored.
        The formatting options only apply when previewing or viewing the page in normal mode.
      -->
      Date formatting (same parameters as date pipe):&nbsp;
      <span *scDate="rendering.fields.date; format: 'full'"></span>
    </li>
    <li>
      Time zones and locales:&nbsp;
      <span *scDate="rendering.fields.date; format: 'full'; timezone: '-0400'; locale: 'en-US'"></span>
    </li>
  </ul>
</app-styleguide-specimen>

// samples/nextjs/src/components/Styleguide-FieldUsage-Date/index.tsx
import { ComponentRendering, DateField, Field } from '@sitecore-jss/sitecore-jss-nextjs';
import StyleguideSpecimen from 'components/Styleguide-Specimen';

interface StyleguideFieldUsageDateProps {
  fields: {
    heading: Field<string>;
    description: Field<string>;
    date: Field<string>;
    dateTime: Field<string>;
  };
  rendering: ComponentRendering;
}

/**
 * Demonstrates usage of date and time content field types within JSS.
 */
const StyleguideFieldUsageDate: React.FC<StyleguideFieldUsageDateProps> = (props) => {
  return (
    <StyleguideSpecimen {...props} e2eId="styleguide-fieldusage-date">
      <ul>
        <li>
          Date helper: <DateField field={props.fields.date} />
        </li>
        <li>
          Date helper (datetime): <DateField field={props.fields.dateTime} />
        </li>
        <li>
          UTC Date string:&nbsp;
          {/*
            Date helper supports a render props API to give you direct access to the JS Date object for formatting.
            IMPORTANT: the render prop is ignored when in Experience Editor mode to support inline editing.
          */}
          <DateField field={props.fields.date} render={(date) => date && date.toUTCString()} />
        </li>
        <li>
          Localized Date string (local timezone):&nbsp;
          <DateField
            field={props.fields.date}
            render={(date) => date && date.toLocaleDateString()}
          />
        </li>
        <li>
          Localized DateTime string (local timezone):&nbsp;
          {/* React components can also be returned from the render props for wrapping */}
          <DateField
            field={props.fields.dateTime}
            render={(date) => <em>{date && date.toLocaleString()}</em>}
          />
        </li>
      </ul>
    </StyleguideSpecimen>
  );
};

export default StyleguideFieldUsageDate;
