// packages/sitecore-jss-angular/src/components/editframe.component.ts
import { Component, Input, OnChanges } from '@angular/core';
import {
  EditFrameDataSource,
  ChromeCommand,
  EditButtonTypes,
  mapButtonToCommand,
} from '@sitecore-jss/sitecore-jss/utils';
import { LayoutServiceContextData, RouteData } from '@sitecore-jss/sitecore-jss/layout';

@Component({
  selector: 'sc-edit-frame,[sc-edit-frame]',
  template:
    '<div *ngIf="isEditing; else elseBlock" {{...frameProps}}><span class="scChromeData">{{chromeData}}</span><ng-content></ng-content></div><ng-template #elseBlock><ng-content></ng-content></ng-template>',
})
export class EditFrameComponent implements OnChanges {
  @Input() dataSource: EditFrameDataSource;

  @Input() buttons: EditButtonTypes[];

  @Input() title: string;

  @Input() tooltip: string;

  @Input() cssClass: string;

  @Input() parameters: Record<string, string | number | boolean | undefined | null>;

  @Input() sitecore: LayoutServiceContextData & {
    route: RouteData | null;
  };

  isEditing = false;
  frameProps: Record<string, unknown> = {};
  chromeData = '';

  ngOnChanges() {
    this.isEditing = this.sitecore.context.pageEditing || false;
    if (!this.isEditing) {
      return;
    }

    const chromeData: Record<string, unknown> = {
      displayName: this.title,
      expandedDisplayName: this.tooltip,
    };

    this.frameProps.class = 'scLooseFrameZone';
    if (this.cssClass) {
      this.frameProps.class = `${this.frameProps.class} ${this.cssClass}`;
    }

    // item uri for edit frame target
    if (this.dataSource) {
      const route = this.sitecore.route;
      const databaseName = this.dataSource.databaseName || route?.databaseName;
      const language = this.dataSource.language || this.sitecore.context.language;
      this.frameProps.sc_item = `sitecore://${databaseName}/${this.dataSource.itemId}?lang=${language}`;
      chromeData.contextItemUri = this.frameProps.sc_item;
    }

    chromeData.commands = this.buttons?.map(
      (value): ChromeCommand => {
        return mapButtonToCommand(value, this.dataSource?.itemId, this.parameters);
      }
    );

    this.chromeData = JSON.stringify(chromeData);
  }
}

// packages/sitecore-jss-react/src/components/EditFrame.tsx
import React, { PropsWithChildren } from 'react';
import { useSitecoreContext } from '../enhancers/withSitecoreContext';
import {
  EditFrameDataSource,
  ChromeCommand,
  EditButtonTypes,
  mapButtonToCommand,
} from '@sitecore-jss/sitecore-jss/utils';

export interface EditFrameProps {
  dataSource?: EditFrameDataSource;
  buttons?: EditButtonTypes[];
  title?: string;
  tooltip?: string;
  cssClass?: string;
  parameters?: Record<string, string | number | boolean | undefined | null>;
}

export const EditFrame: React.FC<PropsWithChildren<EditFrameProps>> = ({
  children,
  dataSource,
  buttons,
  title,
  tooltip,
  cssClass,
  parameters,
}: PropsWithChildren<EditFrameProps>) => {
  const { sitecoreContext } = useSitecoreContext();

  if (!sitecoreContext.pageEditing) {
    return <>{children}</>;
  }

  const chromeData: Record<string, unknown> = {
    displayName: title,
    expandedDisplayName: tooltip,
  };

  const frameProps: Record<string, unknown> = {};
  frameProps.className = 'scLooseFrameZone';
  if (cssClass) {
    frameProps.className = `${frameProps.className} ${cssClass}`;
  }

  // item uri for edit frame target
  if (dataSource) {
    const databaseName = dataSource.databaseName || sitecoreContext.route?.databaseName;
    const language = dataSource.language || sitecoreContext.language;
    frameProps.sc_item = `sitecore://${databaseName}/${dataSource.itemId}?lang=${language}`;
    chromeData.contextItemUri = frameProps.sc_item;
  }

  chromeData.commands = buttons?.map(
    (value): ChromeCommand => {
      return mapButtonToCommand(value, dataSource?.itemId, parameters);
    }
  );

  return (
    <div className="scLooseFrameZone" {...frameProps}>
      <span className="scChromeData">{JSON.stringify(chromeData)}</span>
      {children}
    </div>
  );
};
