// packages/create-sitecore-jss/src/templates/react/src/components/Styleguide-FieldUsage-Checkbox/index.js
import React from 'react';
import { getFieldValue } from '@sitecore-jss/sitecore-jss-react';
import StyleguideSpecimen from '../Styleguide-Specimen';

/**
 * Demonstrates usage of a Checkbox (boolean) content field within JSS.
 */
const StyleguideFieldUsageCheckbox = (props) => (
  <StyleguideSpecimen {...props} e2eId="styleguide-fieldusage-checkbox">
    {/* Checkbox fields do not have the ability to be inline edited, so they are directly accessed via their value: */}
    <ul>
      {/*
        The getFieldValue helper allows safely extracting a field value that could be undefined,
        without needing to check that props.fields or props.fields.checkbox are traversable,
        and allowing the specification of an optional default value (default is undefined if unspecified).
       */}
      {props.fields && props.fields.checkbox && props.fields.checkbox.value && (
        <li>
          <code>checkbox</code> is true
        </li>
      )}
      {!props.fields ||
        !props.fields.checkbox ||
        (!props.fields.checkbox.value && (
          <li>
            <code>checkbox</code> is false
          </li>
        ))}
      {getFieldValue(props.fields, 'checkbox2', false) && (
        <li>
          <code>checkbox2</code> is true
        </li>
      )}
      {!getFieldValue(props.fields, 'checkbox2', false) && (
        <li>
          <code>checkbox2</code> is false
        </li>
      )}
    </ul>
  </StyleguideSpecimen>
);

export default StyleguideFieldUsageCheckbox;

// packages/create-sitecore-jss/src/templates/angular-sxp/src/app/components/styleguide-field-usage-checkbox/styleguide-field-usage-checkbox.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { ComponentRendering, getFieldValue } from '@sitecore-jss/sitecore-jss-angular';

/**
 * Demonstrates usage of a Checkbox (boolean) content field within JSS.
 */
@Component({
  selector: 'app-styleguide-field-usage-checkbox',
  templateUrl: './styleguide-field-usage-checkbox.component.html',
})
export class StyleguideFieldUsageCheckboxComponent implements OnInit {
  @Input() rendering: ComponentRendering;
  checkbox1Value: boolean;
  checkbox2Value: boolean;

  constructor() { }

  ngOnInit() {
    /*
      The getFieldValue helper allows safely extracting a field value that could be undefined,
      without needing to check that props.fields or props.fields.checkbox are traversable,
      and allowing the specification of an optional default value (default is undefined if unspecified).
    */
   this.checkbox1Value = getFieldValue<boolean>(this.rendering, 'checkbox');
   this.checkbox2Value = getFieldValue<boolean>(this.rendering, 'checkbox2');
  }
}

<app-styleguide-specimen [rendering]="rendering" e2eId="styleguide-fieldusage-checkbox">
  <!-- Checkbox fields do not have the ability to be inline edited, so they are directly accessed via their value: -->
    <ul>
      <li>
        <code>checkbox</code> is {{ checkbox1Value }}
      </li>
      <li>
        <code>checkbox2</code> is {{ checkbox2Value }}
      </li>
    </ul>
</app-styleguide-specimen>
