// packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/image/image.component.ts
import { Component, OnInit, OnDestroy, ViewChild, TemplateRef } from '@angular/core';
import { Subscription } from 'rxjs';
import { EditMode, ImageField } from '@sitecore-jss/sitecore-jss-angular';
import { SxaComponent } from '../sxa.component';
import { JssContextService } from '../../jss-context.service';

@Component({
  selector: 'app-image',
  templateUrl: './image.component.html',
})
export class ImageComponent extends SxaComponent implements OnInit, OnDestroy {
  @ViewChild('default', { static: true }) defaultVariant: TemplateRef<any>;
  @ViewChild('banner', { static: true }) bannerVariant: TemplateRef<any>;
  classHeroBannerEmpty = '';
  backgroundStyle = {};
  modifyImageProps = {};
  isEditing = false;
  private contextSubscription: Subscription;

  constructor(private jssContext: JssContextService) {
    super();
  }

  ngOnInit() {
    super.ngOnInit();

    const imageField = this.rendering.fields?.Image as ImageField;
    this.backgroundStyle = imageField?.value?.src && {
      'background-image': `url('${imageField.value.src}')`,
    };

    this.contextSubscription = this.jssContext.state.subscribe((newState) => {
      this.isEditing = newState.sitecore && newState.sitecore.context.pageEditing;

      this.classHeroBannerEmpty =
        this.isEditing && imageField?.value?.class === 'scEmptyImage' ? 'hero-banner-empty' : '';

      const isMetadataMode = newState.sitecore?.context?.editMode === EditMode.Metadata;
      this.modifyImageProps = !isMetadataMode
        ? {
            ...imageField,
            editable: imageField?.editable
              ?.replace(`width="${imageField?.value?.width}"`, 'width="100%"')
              .replace(`height="${imageField?.value?.height}"`, 'height="100%"'),
          }
        : {
            ...imageField,
            value: {
              ...imageField?.value,
              style: { width: '100%', height: '100%' },
            },
          };
    });
  }

  ngOnDestroy() {
    if (this.contextSubscription) {
      this.contextSubscription.unsubscribe();
    }
  }

  public get variant(): TemplateRef<any> {
    return this.rendering.params?.FieldNames === 'Banner'
      ? this.bannerVariant
      : this.defaultVariant;
  }
}

<ng-container [ngTemplateOutlet]="variant"></ng-container>

<ng-template #default>
  <div class="component image {{ styles }}" [attr.id]="id" *ngIf="rendering.fields; else empty">
    <div class="component-content">
      <ng-container *ngIf="isEditing || !rendering.fields.TargetUrl?.value?.href; else withLink">
        <img *scImage="rendering.fields.Image" />
      </ng-container>
      <span class="image-caption field-imagecaption" *scText="rendering.fields.ImageCaption"></span>
    </div>
  </div>
</ng-template>

<ng-template #banner>
  <div class="component hero-banner {{ styles }} {{ classHeroBannerEmpty }}" [attr.id]="id">
    <div class="component-content sc-sxa-image-hero-banner" [ngStyle]="backgroundStyle">
      <ng-container *ngIf="isEditing">
        <img *scImage="modifyImageProps" />
      </ng-container>
    </div>
  </div>
</ng-template>

<ng-template #withLink>
  <a *scGenericLink="rendering.fields.TargetUrl">
    <img *scImage="rendering.fields.Image" />
  </a>
</ng-template>

<ng-template #empty>
  <div class="component image {{ styles }}">
    <div class="component-content">
      <span class="is-empty-hint">Image</span>
    </div>
  </div>
</ng-template>

// samples/nextjs/src/components/Image.tsx
import {
  EditMode,
  Field,
  ImageField,
  NextImage as JssImage,
  Link as JssLink,
  LinkField,
  Text,
  useSitecoreContext,
} from '@sitecore-jss/sitecore-jss-nextjs';
import React, { CSSProperties } from 'react';

interface Fields {
  Image: ImageField & { metadata?: { [key: string]: unknown } };
  ImageCaption: Field<string>;
  TargetUrl: LinkField;
}

type ImageProps = {
  params: { [key: string]: string };
  fields: Fields;
};

const ImageDefault = (props: ImageProps): JSX.Element => (
  <div className={`component image ${props.params.styles}`.trimEnd()}>
    <div className="component-content">
      <span className="is-empty-hint">Image</span>
    </div>
  </div>
);

export const Banner = (props: ImageProps): JSX.Element => {
  const id = props.params.RenderingIdentifier;
  const { sitecoreContext } = useSitecoreContext();
  const isPageEditing = sitecoreContext.pageEditing;
  const isMetadataMode = sitecoreContext?.editMode === EditMode.Metadata;
  const classHeroBannerEmpty =
    isPageEditing && props.fields?.Image?.value?.class === 'scEmptyImage'
      ? 'hero-banner-empty'
      : '';
  const backgroundStyle = (props?.fields?.Image?.value?.src && {
    backgroundImage: `url('${props.fields.Image.value.src}')`,
  }) as CSSProperties;
  const modifyImageProps = !isMetadataMode
    ? {
        ...props.fields.Image,
        editable: props?.fields?.Image?.editable
          ?.replace(`width="${props?.fields?.Image?.value?.width}"`, 'width="100%"')
          .replace(`height="${props?.fields?.Image?.value?.height}"`, 'height="100%"'),
      }
    : {
        ...props.fields.Image,
        value: {
          ...props.fields.Image.value,
          style: { width: '100%', height: '100%' },
        },
      };

  return (
    <div
      className={`component hero-banner ${props.params.styles} ${classHeroBannerEmpty}`}
      id={id ? id : undefined}
    >
      <div className="component-content sc-sxa-image-hero-banner" style={backgroundStyle}>
        {sitecoreContext.pageEditing ? <JssImage field={modifyImageProps} /> : ''}
      </div>
    </div>
  );
};

export const Default = (props: ImageProps): JSX.Element => {
  const { sitecoreContext } = useSitecoreContext();

  if (props.fields) {
    const Image = () => <JssImage field={props.fields.Image} />;
    const id = props.params.RenderingIdentifier;

    return (
      <div className={`component image ${props.params.styles}`} id={id ? id : undefined}>
        <div className="component-content">
          {sitecoreContext.pageState === 'edit' || !props.fields.TargetUrl?.value?.href ? (
            <Image />
          ) : (
            <JssLink field={props.fields.TargetUrl}>
              <Image />
            </JssLink>
          )}
          <Text
            tag="span"
            className="image-caption field-imagecaption"
            field={props.fields.ImageCaption}
          />
        </div>
      </div>
    );
  }

  return <ImageDefault {...props} />;
};
