// packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/richtext/richtext.component.ts
﻿import { Component, Input, OnInit } from '@angular/core';
import { ComponentRendering } from '@sitecore-jss/sitecore-jss-angular';

@Component({
  selector: 'app-richtext',
  templateUrl: './richtext.component.html',
})
export class RichTextComponent implements OnInit {
  @Input() rendering: ComponentRendering;
  text: string;
  id: string;
  styles: string;

  ngOnInit() {
    this.text = this.rendering.fields.Text;
    this.id = this.rendering.params.RenderingIdentifier;
    this.styles = this.rendering.params?.styles?.trimEnd();
  }
}

﻿<div
  class="component rich-text {{ styles }}"
  [attr.id]="id"
>
  <div class="component-content">
    <ng-container *ngIf="text; else emptyHint">
      <div *scRichText="text"></div>
    </ng-container>
    <ng-template #emptyHint>
      <span class="is-empty-hint">Rich text</span>
    </ng-template>
  </div>
</div>

// samples/nextjs/src/components/RichText.tsx
import React from 'react';
import {
  RenderingVariants,
  RenderingVariantProps,
  RenderingVariantParameters,
  Field,
  RichText as JssRichText,
  Text,
  ComponentRendering,
} from '@sitecore-jss/sitecore-jss-nextjs';

interface Fields {
  Text: Field<string>;
  Title: Field<string>;
}

interface ComponentProps {
  rendering: ComponentRendering & { params: RenderingVariantParameters };
  params: RenderingVariantParameters;
  fields: Fields;
}

const RichText = (props: ComponentProps): JSX.Element => {
  return (
    <RenderingVariants
      fields={props.fields}
      componentName={props.rendering.componentName}
      params={props.rendering.params}
    />
  );
};

export const Default = (props: RenderingVariantProps<Fields>): JSX.Element => {
  if (props.fields) {
    return (
      <div className={`component rich-text ${props.styles?.replace(/\|/g, ' ')}`}>
        <div className="component-content">
          <JssRichText field={props.fields.Text} />
        </div>
      </div>
    );
  } else {
    return (
      <div className={`component rich-text ${props.styles?.replace(/\|/g, ' ')}`}>
        <div className="component-content"> 
          <span className="is-empty-hint">Rich text</span>
        </div>
      </div>
    )
  }    
};

export default RichText;
