// samples/vue/src/components/Styleguide/Styleguide-FieldUsage-Date.vue
<!--
  Demonstrates usage of date and time content field types within JSS.
-->
<template>
  <styleguide-specimen v-bind="$props">
    <ul>
      <li>
        Date helper: <sc-date :field="fields.date" />
      </li>
      <li>
        Date helper (datetime): <sc-date :field="fields.dateTime" />
      </li>
      <li>
        UTC Date string:&nbsp;
        <!--
          Date helper provides a `formatter` prop to give you direct access to the JS Date object for formatting.
          IMPORTANT: the formatter prop is ignored when in Experience Editor mode to support inline editing.
        -->
        <sc-date :field="fields.date" :formatter="(date) => date ? date.toUTCString() : null" />
      </li>
      <li>
        Localized Date string (local timezone):&nbsp;
        <sc-date :field="fields.date" :formatter="(date) => date ? date.toLocaleDateString() : null" />
      </li>
      <li>
        Localized DateTime string (local timezone):&nbsp;
        <!--
          Date helper also has a scoped slot that allows more granular control over the rendered output.
          For instance, you may wish to wrap the value in custom markup.
          IMPORTANT: the scoped slot is ignored when in Experience Editor mode to support inline editing.
        -->
        <sc-date
          :field="fields.dateTime">
          <em slot-scope="date">{{ date ? date.toLocaleDateString() : null }}</em>
        </sc-date>
      </li>
    </ul>
  </styleguide-specimen>
</template>

<script>
import { DateField } from '@sitecore-jss/sitecore-jss-vue';
import StyleguideSpecimen from './Styleguide-Specimen';

export default {
  name: 'Styleguide-FieldUsage-Date',
  props: {
    fields: {
      type: Object,
    },
    rendering: {
      type: Object,
    },
  },
  components: {
    ScDate: DateField,
    StyleguideSpecimen,
  },
};
</script>

// samples/react/src/components/Styleguide-FieldUsage-Date/index.js
import React from 'react';
import { DateField } from '@sitecore-jss/sitecore-jss-react';
import StyleguideSpecimen from '../Styleguide-Specimen';

/**
 * Demonstrates usage of date and time content field types within JSS.
 */
const StyleguideFieldUsageDate = (props) => {
  return (
    <StyleguideSpecimen {...props}>
      <ul>
        <li>
          Date helper: <DateField field={props.fields.date} />
        </li>
        <li>
          Date helper (datetime): <DateField field={props.fields.dateTime} />
        </li>
        <li>
          UTC Date string:&nbsp;
          {/*
            Date helper supports a render props API to give you direct access to the JS Date object for formatting.
            IMPORTANT: the render prop is ignored when in Experience Editor mode to support inline editing.
          */}
          <DateField field={props.fields.date} render={(date) => date.toUTCString()} />
        </li>
        <li>
          Localized Date string (local timezone):&nbsp;
          <DateField field={props.fields.date} render={(date) => date.toLocaleDateString()} />
        </li>
        <li>
          Localized DateTime string (local timezone):&nbsp;
          {/* React components can also be returned from the render props for wrapping */}
          <DateField
            field={props.fields.dateTime}
            render={(date) => <em>{date.toLocaleString()}</em>}
          />
        </li>
      </ul>
    </StyleguideSpecimen>
  );
};

export default StyleguideFieldUsageDate;
