// packages/sitecore-jss-react-forms/src/components/field-templates/checkbox-list.tsx
import React, { Fragment } from 'react';
import { FieldValidationErrors } from './field-validation-errors';
import { Label } from './label';
import { FieldChangeCallback, ListFieldProps } from '../../FieldProps';
import { ValueFormField } from '@sitecore-jss/sitecore-jss-forms';

const CheckboxList: React.FunctionComponent<ListFieldProps> = (props) => {
  const {
    field,
    field: {
      model: { items },
    },
    value,
    onChange,
    errors,
    tracker,
  } = props;
  return (
    <Fragment>
      <Label {...props} />
      {items.map((item, index) => (
        <label key={item.itemId}>
          <input
            type="checkbox"
            className={field.model.cssClass}
            id={field.valueField.id + index}
            name={field.valueField.name}
            value={item.value}
            checked={value.some((v) => v === item.value)}
            onChange={(e) =>
              handleOnChange(field, value, e.target.value, e.target.checked, onChange)
            }
            onFocus={() => tracker.onFocusField(field, value)}
            onBlur={() => tracker.onBlurField(field, value, errors)}
          />
          {item.text}
        </label>
      ))}

      <FieldValidationErrors {...props} />
    </Fragment>
  );
};

function handleOnChange(
  field: ValueFormField,
  originalFieldValue: string[],
  changedElement: string,
  checked: boolean,
  callback: FieldChangeCallback
) {
  // we can have multiple selected values. So we need to push ALL the selected
  // values back up to the root form. This is done using an array, which the form
  // serializer knows how to expand into multiple values on post

  let value = originalFieldValue;

  if (checked) {
    value.push(changedElement);
  } else {
    value = value.filter((v) => v !== changedElement);
  }

  // (fieldName, fieldValue, isValid, validationErrors)
  callback(field.valueField.name, value, true, []);
}

export default CheckboxList;

// packages/sitecore-jss-angular-forms/src/app/components/forms/fields/checkbox-list/checkbox-list.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { ValueFormField, ListViewModel, ListFieldItem, FormTracker } from '@sitecore-jss/sitecore-jss-forms';
import { FormStateService } from '../../services/form-state.service';


@Component({
  selector: 'app-checkbox-list',
  templateUrl: './checkbox-list.component.html',
  styleUrls: ['./checkbox-list.component.scss']
})
export class CheckboxListComponent implements OnInit {
  field: ValueFormField<ListViewModel>;
  group: FormGroup;
  tracker: FormTracker;
  value: string[];

  public items: ListFieldItem[];

  public constructor(private formState: FormStateService) { }

  public ngOnInit(): void { 
    this.items = this.field.model.items;

    this.value = this.items
      .filter(i => i.selected)
      .map(i => i.value);
  }

  onChange($event): void {
    let valid = true;
    const errorMessages = [];

    if ($event.target.checked) {
      this.value.push($event.target.value);
    }
    else {
      this.value.filter(v => v !== $event.target.value);
    }

    if (this.field.model.required && !this.value.length) {
      valid = false;
      errorMessages.push(`${this.field.model.title} is required`);
    }

    this.formState.setFieldState(this.field.valueField.name, $event.target.value, valid, errorMessages);
  }

  onFocus($event): void {
    this.tracker.onFocusField(this.field, <string>this.field.model.value);
  }

  onBlur($event): void {
    this.tracker.onBlurField(this.field, <string>this.field.model.value);
  }
}

<app-label [title]="field.model.title" [class]="field.model.labelCssClass"></app-label>
<ul>
  <li *ngFor="let option of items; let idx = index;">
    <input
      type="checkbox"
      [ngClass]="field.model.cssClass" 
      [id]="field.valueField.id + idx" 
      [name]="field.valueField.name"
      [value]="option.value"
      [checked]="option.selected"
      (change)="onChange($event)"
      (focus)="onFocus($event)"
      (blur)="onBlur($event)" 
    />{{option.text}}
  </li>
</ul>
