// packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/RowSplitter.tsx
import React from 'react';
import {
  ComponentParams,
  ComponentRendering,
  Placeholder,
} from '@sitecore-jss/sitecore-jss-nextjs';

interface ComponentProps {
  rendering: ComponentRendering & { params: ComponentParams };
  params: ComponentParams;
}

export const Default = (props: ComponentProps): JSX.Element => {
  const styles = `${props.params.GridParameters ?? ''} ${props.params.Styles ?? ''}`.trimEnd();
  const rowStyles = [
    props.params.Styles1,
    props.params.Styles2,
    props.params.Styles3,
    props.params.Styles4,
    props.params.Styles5,
    props.params.Styles6,
    props.params.Styles7,
    props.params.Styles8,
  ];
  const enabledPlaceholders = props.params.EnabledPlaceholders.split(',');

  return (
    <div className={`component row-splitter ${styles}`}>
      {enabledPlaceholders.map((ph, index) => {
        const phKey = `row-${ph}-{*}`;
        const phStyles = `${rowStyles[+ph - 1] ?? ''}`.trimEnd();

        return (
          <div key={index} className={`container-fluid ${phStyles}`.trimEnd()}>
            <div key={index}>
              <div key={index} className="row">
                <Placeholder key={index} name={phKey} rendering={props.rendering} />
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
};

// packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/row-splitter/row-splitter.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { JssModule } from '@sitecore-jss/sitecore-jss-angular';
import { SxaComponent } from '../sxa.component';

@Component({
  selector: 'app-row-splitter',
  templateUrl: './row-splitter.component.html',
  imports: [CommonModule, JssModule],
  host: {
    "class": "component row-splitter",
    "[class]": "rowSplitterStyles",
    "[id]": "id"
  }
})
export class RowSplitterComponent extends SxaComponent {
  get rowSplitterStyles(): string {
    return `${this.rendering.params.GridParameters ?? ''} ${this.rendering.params.Styles ??
      ''}`.trimEnd();
  }

  get rowStyles(): string[] {
    return Array.from({ length: 8 }, (_, i) => this.rendering.params[`Styles${i + 1}`]);
  }

  get enabledPlaceholders(): string[] {
    return this.rendering.params.EnabledPlaceholders.split(',');
  }

  getRowClass(index: number): string {
    const styleClass = this.rowStyles[index] || '';
    return `${styleClass}`.trim();
  }

  getPlaceholderName(ph: string): string {
    return `row-${ph}-{*}`;
  }
}

<div class="component row-splitter" [ngClass]="rowSplitterStyles" [attr.id]="id">
  <div *ngFor="let ph of enabledPlaceholders" class="container-fluid" [ngClass]="getRowClass(+ph - 1)">
    <div>
      <div class="row">
        <sc-placeholder [name]="getPlaceholderName(ph)" [rendering]="rendering">
        </sc-placeholder>
      </div>
    </div>
  </div>
</div>
