// packages/create-sitecore-jss/src/templates/vue/src/NotFound.vue
<template>
  <metainfo>
    <template v-slot:title="{ content }">{{ content }}</template>
  </metainfo>
  <div>
    <h1>Page not found</h1>
    <p>This page does not exist.</p>
    <p v-if="context && context.site">
      Site: {{ context.site.name }}
      <br />
      Language: {{ context.language }}
    </p>
  </div>
</template>

<script>
import { useI18n } from 'vue-i18n';
import { useMeta } from 'vue-meta';

export default {
  name: 'not-found',
  setup() {
    const { t } = useI18n();
    useMeta({
      title: t('page-not-found'),
    });
  },
  props: {
    context: {
      type: Object,
    },
  },
};
</script>

// packages/create-sitecore-jss/src/templates/angular/src/app/routing/not-found/not-found.component.ts
import { Component, Input } from '@angular/core';
import { LayoutServiceContextData } from '@sitecore-jss/sitecore-jss-angular';

@Component({
  selector: 'app-not-found',
  templateUrl: './not-found.component.html'
})
export class NotFoundComponent {
  @Input() errorContextData: LayoutServiceContextData;
}

<h1>Not found</h1>
<p>This page does not exist.</p>
<p>
  Site: {{errorContextData?.context?.site?.name}}
  <br />
  Language: {{errorContextData?.context?.language}}
</p>
