// samples/basic-sample-vue-web/src/app/components/Welcome.vue
<template>
  <div id="CenterColumn">
    <div id="InnerCenter">
      <div id="Header">
        <sc-image :media="fields.logoImage" id="scLogo" />
      </div>
      <div id="Content">
        <div id="LeftContent">
          <sc-text tag="h1" :field="fields.title" class="contentTitle" />
          <sc-rich-text class="contentDescription" :field="fields.text" />
        </div>
      </div>
      <div id="Footer">
        <hr class="divider" />
        {{ copyright }}
      </div>
    </div>
  </div>
</template>

<script>
import { Image, Text, RichText } from '@sitecore-jss/sitecore-jss-vue';

export default {
  name: 'Welcome',
  props: {
    fields: {
      type: Object,
      default: () => ({}),
    },
    copyright: {
      type: String,
      default: 'Copyright Sitecore A/S',
    },
  },
  components: {
    ScImage: Image,
    ScText: Text,
    ScRichText: RichText,
  },
};
</script>

<style>

</style>

// samples/basic-sample-react/src/app/components/Welcome.js
import React from 'react';
import PropTypes from 'prop-types';
import { Image, RichText } from '@sitecore-jss/sitecore-jss-react';

const Welcome = ({ fields, copyright }) =>
  <div id="CenterColumn">
    <div id="InnerCenter">
      <div id="Header">
        <Image media={fields.logoImage} id="scLogo" />
      </div>
      <div id="Content">
        <div id="LeftContent">
          <RichText tag="h1" className="contentTitle" field={fields.title} />
          <RichText className="contentDescription" field={fields.text} />
        </div>
      </div>
      <div id="Footer">
        <hr className="divider" />
        {copyright}
      </div>
    </div>
  </div>;

Welcome.propTypes = {
  fields: PropTypes.shape({
    title: PropTypes.shape({
      value: PropTypes.string,
      editable: PropTypes.string,
    }),
    text: PropTypes.shape({
      value: PropTypes.string,
      editable: PropTypes.string,
    }),
    logoImage: PropTypes.shape({
      value: PropTypes.shape({
        src: PropTypes.string,
      }),
      editable: PropTypes.string,
    }),
  }),
  copyright: PropTypes.string
};

Welcome.defaultProps = {
  copyright: "Copyright Sitecore A/S"
};

export default Welcome;
