// packages/sitecore-jss-react/src/components/HiddenRendering.tsx
import React from 'react';

const styles = {
  height: '100px',
  backgroundImage:
    'linear-gradient(45deg, #ffffff 25%, #dcdcdc 25%, #dcdcdc 50%, #ffffff 50%, #ffffff 75%, #dcdcdc 75%, #dcdcdc 100%)',
  backgroundSize: '3px 3px',
};

export const HiddenRendering = () => <div style={styles} />;

export const HIDDEN_RENDERING_NAME = 'Hidden Rendering';

// packages/sitecore-jss-angular/src/components/hidden-rendering.component.ts
import { Component } from '@angular/core';
@Component({
  selector: 'sc-hidden-rendering',
  host: {
    style:
      'display: block; height: 100px; background-image: linear-gradient(45deg, #ffffff 25%, #dcdcdc 25%, #dcdcdc 50%, #ffffff 50%, #ffffff 75%, #dcdcdc 75%, #dcdcdc 100%); backgroundSize: 3px 3px;',
  },
  template: ''
})
export class HiddenRenderingComponent {}

export const HIDDEN_RENDERING_NAME = 'Hidden Rendering';
