// samples/embedded-wizard-sample-react/src/app/index.js
import React from "react";
import PropTypes from "prop-types";
import { Placeholder } from "@sitecore-jss/sitecore-jss-react";

import css from "assets/css/app.css";

const App = ({ route }) => <Placeholder name="main" rendering={route} />;

App.propTypes = {
  route: PropTypes.object
};

export default App;

// samples/basic-sample-vue-web/src/app/App.vue
<template>
  <div>
    <placeholder name="main" :rendering="route" />
  </div>
</template>

<script>
import { Placeholder } from '@sitecore-jss/sitecore-jss-vue';
import '../../assets/css/default.css';

export default {
  name: 'App',
  props: {
    route: {
      type: Object,
      default: () => ({}),
    },
  },
  components: {
    Placeholder,
  },
};
</script>

<style>

</style>
