// packages/sitecore-jss-react-forms/src/components/field-templates/single-line-text.tsx
import React, { Fragment } from 'react';
import { FieldValidationErrors } from './field-validation-errors';
import { Label } from './label';
import { ValueFieldProps, FieldChangeCallback } from '../../FieldProps';
import { StringInputViewModel, ValueFormField } from '@sitecore-jss/sitecore-jss-forms';

const SingleLineText: React.FunctionComponent<ValueFieldProps<StringInputViewModel>> = (props) => {
  const { field, value, onChange, errors, tracker } = props;

  return (
    <Fragment>
      <Label {...props} />
      <input
        type="text"
        className={field.model.cssClass}
        id={field.valueField.id}
        name={field.valueField.name}
        value={value}
        maxLength={field.model.maxLength}
        placeholder={field.model.placeholderText}
        onChange={(e) => handleOnChange(field, e.target.value, onChange)}
        onFocus={() => tracker.onFocusField(field, value)}
        onBlur={() => tracker.onBlurField(field, value, errors)}
      />
      <FieldValidationErrors {...props} />
    </Fragment>
  );
};

function handleOnChange(field: ValueFormField, fieldValue: string, callback: FieldChangeCallback) {
  let valid = true;
  const errorMessages = [];

  // custom client validation logic here
  if (field.model.required && !fieldValue) {
    valid = false;
    errorMessages.push(`${field.model.title} is required`);
  }

  callback(field.valueField.name, fieldValue, valid, errorMessages);
}

export default SingleLineText;

// packages/sitecore-jss-angular-forms/src/app/components/forms/fields/single-line-text/single-line-text.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { ValueFormField, StringInputViewModel, FormTracker } from '@sitecore-jss/sitecore-jss-forms';
import { FormStateService } from '../../services/form-state.service';

@Component({
  selector: 'app-single-line-text',
  templateUrl: './single-line-text.component.html'
})

export class SingleLineTextComponent implements OnInit {
  field: ValueFormField<StringInputViewModel>;
  group: FormGroup;
  tracker: FormTracker; 

  public constructor(private formState: FormStateService) { }

  public ngOnInit(): void { }

  onChange($event): void {
    let valid = true;
    const errorMessages = [];

    // custom client validation logic here
    if (this.field.model.required && !$event.target.value) {
      valid = false;
      errorMessages.push(`${this.field.model.title} is required`);
    }

    this.formState.setFieldState(this.field.valueField.name, $event.target.value, valid, errorMessages);
  }

  onFocus($event): void {
    this.tracker.onFocusField(this.field, $event.target.value);
  }

  onBlur($event): void {
    this.tracker.onBlurField(this.field, $event.target.value);
  }
}

<app-label [title]="field.model.title" [class]="field.model.labelCssClass"></app-label>
<input 
  type="text"
  [ngClass]="field.model.cssClass"
  [id]="field.valueField.id" 
  [name]="field.valueField.name"
  [value]="field.model.value" 
  [maxLength]="field.model.maxLength" 
  [placeholder]="field.model.placeholderText"
  (change)="onChange($event)"
  (focus)="onFocus($event)"
  (blur)="onBlur($event)">

<!-- <ng-container *ngFor="let validation of field.validations;" ngProjectAs="mat-error">
  <mat-error *ngIf="group.get(field.name).hasError(validation.name)">{{validation.message}}</mat-error>
</ng-container> -->
