// packages/create-sitecore-jss/src/templates/angular-sxp/src/app/components/styleguide-field-usage-file/styleguide-field-usage-file.component.ts
import { Component, Input } from '@angular/core';
import { ComponentRendering, JssModule } from '@sitecore-jss/sitecore-jss-angular';
import { StyleguideSpecimenComponent } from '../shared/styleguide-specimen/styleguide-specimen.component';

/**
 * Demonstrates usage of a File content field within JSS.
 * File types are stored within Sitecore's Media Library data, and can be edited.
 */
@Component({
  selector: 'app-styleguide-field-usage-file',
  templateUrl: './styleguide-field-usage-file.component.html',
  imports: [JssModule, StyleguideSpecimenComponent]
})
export class StyleguideFieldUsageFileComponent {
  @Input() rendering: ComponentRendering;
}

<app-styleguide-specimen [rendering]="rendering" e2eId="styleguide-fieldusage-file">
  <!-- Renders a file link -->
    <a *scFile="rendering.fields.file"></a>
    <br />

  <!-- Renders a file link with a custom body and opening in a new tab -->
  <a *scFile="rendering.fields.file" target="_blank">
    Custom link body
  </a>
</app-styleguide-specimen>

// packages/create-sitecore-jss/src/templates/react/src/components/Styleguide-FieldUsage-File/index.js
import React from 'react';
import { File } from '@sitecore-jss/sitecore-jss-react';
import StyleguideSpecimen from '../Styleguide-Specimen';

/**
 * Demonstrates usage of a File content field within JSS.
 * File types are stored within Sitecore's Media Library data, and can be edited.
 */
const StyleguideFieldUsageFile = (props) => (
  <StyleguideSpecimen {...props} e2eId="styleguide-fieldusage-file">
    {/* Renders a file link */}
    <File field={props.fields.file} />
    <br />

    {/* Renders a file link with a custom body and opening in a new tab */}
    <File field={props.fields.file} target="_blank">
      Custom link body
    </File>
  </StyleguideSpecimen>
);

export default StyleguideFieldUsageFile;
