// packages/create-sitecore-jss/src/templates/angular-sxp/src/app/components/styleguide-field-usage-item-link/styleguide-field-usage-item-link.component.ts
import { Component, Input } from '@angular/core';
import { ComponentRendering } from '@sitecore-jss/sitecore-jss-angular';

/**
 * Demonstrates usage of a Content Link content field within JSS.
 * Content links are a reference to a single other piece of content.
 */
@Component({
  selector: 'app-styleguide-field-usage-item-link',
  templateUrl: './styleguide-field-usage-item-link.component.html',
})
export class StyleguideFieldUsageItemLinkComponent {
  @Input() rendering: ComponentRendering;
}

<app-styleguide-specimen [rendering]="rendering" e2eId="styleguide-fieldusage-itemlink">
  <h5>Shared Item Link</h5>
  <!-- Item link fields are returned with their value as the referenced item value. -->
  <ng-container *ngIf="rendering.fields.sharedItemLink">
    <!-- The referenced item's fields can be rendered and edited using normal helper components: -->
    <p>
      Field: <span *scText="rendering.fields.sharedItemLink.fields.textField"></span>
    </p>
  </ng-container>

  <h5>Local Item Link</h5>
  <ng-container *ngIf="rendering.fields.localItemLink">
    <p>
      Field: <span *scText="rendering.fields.localItemLink.fields.textField"></span>
    </p>
  </ng-container>
</app-styleguide-specimen>

// packages/create-sitecore-jss/src/templates/react/src/components/fields/Styleguide-FieldUsage-ItemLink.js
import React from 'react';
import { Text } from '@sitecore-jss/sitecore-jss-react';
import StyleguideSpecimen from '../styleguide/Styleguide-Specimen';

/**
 * Demonstrates usage of a Content Link content field within JSS.
 * Content links are a reference to a single other piece of content.
 */
const StyleguideFieldUsageItemLink = (props) => {
  const { sharedItemLink, localItemLink } = props.fields;

  return (
    <StyleguideSpecimen {...props} e2eId="styleguide-fieldusage-itemlink">
      <h5>Shared Item Link</h5>
      {/*
        Item link fields are returned with their value as the referenced item value.
      */}
      {sharedItemLink && (
        <div>
          {/* The referenced item's fields can be rendered and edited using normal helper components: */}
          <p>
            Field: <Text field={sharedItemLink.fields.textField} />
          </p>
        </div>
      )}

      <h5>Local Item Link</h5>
      {localItemLink && (
        <div>
          <p>
            Field: <Text field={localItemLink.fields.textField} />
          </p>
        </div>
      )}
    </StyleguideSpecimen>
  );
};

export default StyleguideFieldUsageItemLink;
