// packages/create-sitecore-jss/src/templates/angular-sxp/src/app/components/styleguide-field-usage-custom/styleguide-field-usage-custom.component.ts
import { Component, Input } from '@angular/core';
import { ComponentRendering } from '@sitecore-jss/sitecore-jss-angular';
import { StyleguideSpecimenComponent } from '../shared/styleguide-specimen/styleguide-specimen.component';

/**
 * Demonstrates usage of a custom content field type within JSS.
 * See /sitecore/definitions/components/Styleguide-FieldUsage-Custom.sitecore.js
 * for the definition of the structure of the custom field. This code is just for display.
 */
@Component({
  selector: 'app-styleguide-field-usage-custom',
  templateUrl: './styleguide-field-usage-custom.component.html',
  imports: [StyleguideSpecimenComponent]
})
export class StyleguideFieldUsageCustomComponent {
  @Input() rendering: ComponentRendering;
}

<app-styleguide-specimen [rendering]="rendering" e2eId="styleguide-fieldusage-custom">
  <!-- Because the integer field is essentially text, we can render it with the *scText helper -->
  <span *scText="rendering.fields.customIntField"></span>
</app-styleguide-specimen>

// packages/create-sitecore-jss/src/templates/react/src/components/fields/Styleguide-FieldUsage-Custom.js
import React from 'react';
import { Text } from '@sitecore-jss/sitecore-jss-react';
import StyleguideSpecimen from '../styleguide/Styleguide-Specimen';

/**
 * Demonstrates usage of a custom content field type within JSS.
 * See /sitecore/definitions/components/Styleguide-FieldUsage-Custom.sitecore.js
 * for the definition of the structure of the custom field. This code is just for display.
 */
const StyleguideFieldUsageCustom = (props) => (
  <StyleguideSpecimen {...props} e2eId="styleguide-fieldusage-custom">
    {/* Because the integer field is essentially text, we can render it with the Text helper */}
    <Text field={props.fields.customIntField} />
  </StyleguideSpecimen>
);

export default StyleguideFieldUsageCustom;
