// packages/create-sitecore-jss/src/templates/nextjs-styleguide/src/components/styleguide/Styleguide-Multilingual.tsx
import { Text, Field, withDatasourceCheck } from '@sitecore-jss/sitecore-jss-nextjs';
import Link from 'next/link';
import { useI18n } from 'next-localization';
import StyleguideSpecimen from './Styleguide-Specimen';
import { ComponentWithContextProps } from 'lib/component-props';
import { StyleguideSpecimenFields } from 'lib/component-props/styleguide';

type StyleguideMultilingualProps = ComponentWithContextProps &
  StyleguideSpecimenFields & {
    fields: {
      sample: Field<string>;
    };
  };

/**
 * Demonstrates using the dictionary functionality and defining route data in
 * multiple languages.
 */
const StyleguideMultilingual = (props: StyleguideMultilingualProps): JSX.Element => {
  const { t, locale } = useI18n();

  return (
    <StyleguideSpecimen {...props} e2eId="styleguide-multilingual">
      <Text field={props.fields.sample} encode={false} tag="p" />

      <p>
        This is a static dictionary entry from <code>/data/dictionary</code>
        :&nbsp;
        {t('styleguide-sample')}
      </p>

      <p>
        {/* In case if href already includes locale: https://nextjs.org/docs/advanced-features/i18n-routing#transition-between-locales */}
        <Link href="/en/styleguide" locale={false}>
          <a>Show in English</a>
        </Link>
        <br />
        <% if (language) { -%>
        <Link href="/styleguide" locale="<%- language %>">
          <a>Show in <%- language %></a>
        </Link>
        <% } -%>
      </p>

      <p>The current language is: {locale()}</p>
    </StyleguideSpecimen>
  );
};

export default withDatasourceCheck()<StyleguideMultilingualProps>(StyleguideMultilingual);

// packages/create-sitecore-jss/src/templates/vue/src/components/Styleguide/Styleguide-Multilingual.vue
<!--
  Demonstrates using the dictionary functionality and defining route data in
  multiple languages.
-->
<template>
  <styleguide-specimen v-bind="$props" data-e2e-id="styleguide-multilingual">
    <sc-text :field="fields.sample" :encode="false" tag="p" />

    <p>
      <!-- $t is attached to the App instance by the vue-i18n plugin -->
      This is a static dictionary entry from <code>/data/dictionary</code>:&nbsp;{{
        $t('styleguide-sample')
      }}
    </p>

    <p>
      <router-link to="/en/styleguide">Show in English</router-link>
      <br />
      <router-link to="/<%- language %>/styleguide">Show in <%- language %></router-link>
    </p>

    <!-- $i18n is attached to the App instance by the vue-i18n plugin -->
    <p>The current language is: {{ $i18n.locale }}</p>
  </styleguide-specimen>
</template>

<script>
import { Text } from '@sitecore-jss/sitecore-jss-vue';
import StyleguideSpecimen from './Styleguide-Specimen';

export default {
  name: 'Styleguide-Multilingual',
  props: {
    fields: {
      type: Object,
    },
    rendering: {
      type: Object,
    },
  },
  components: {
    StyleguideSpecimen,
    ScText: Text,
  },
};
</script>
