// packages/sitecore-jss-react-forms/src/components/field-templates/number.tsx
import React, { Fragment } from 'react';
import { FieldValidationErrors } from './field-validation-errors';
import { Label } from './label';
import { ValueFieldProps, FieldChangeCallback } from '../../FieldProps';
import { ValueFormField, NumberInputViewModel } from '@sitecore-jss/sitecore-jss-forms';

const NumberField: React.FunctionComponent<ValueFieldProps<NumberInputViewModel>> = (props) => {
  const { field, value, onChange, tracker, errors } = props;

  return (
    <Fragment>
      <Label {...props} />
      <input
        type="number"
        className={field.model.cssClass}
        id={field.valueField.id}
        name={field.valueField.name}
        value={value}
        step={field.model.step}
        min={field.model.min}
        max={field.model.max}
        onChange={(e) => handleOnChange(field, e.target.value, onChange)}
        onFocus={() => tracker.onFocusField(field, value)}
        onBlur={() => tracker.onBlurField(field, value, errors)}
      />
      <FieldValidationErrors {...props} />
    </Fragment>
  );
};

function handleOnChange(field: ValueFormField, fieldValue: string, callback: FieldChangeCallback) {
  let valid = true;
  const errorMessages = [];

  // custom client validation logic here
  if (field.model.required && !fieldValue) {
    valid = false;
    errorMessages.push(`${field.model.title} is required`);
  }

  callback(field.valueField.name, fieldValue, valid, errorMessages);
}

export default NumberField;

// packages/sitecore-jss-angular-forms/src/app/components/forms/fields/number/number.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { ValueFormField, FormTracker } from '@sitecore-jss/sitecore-jss-forms';
import { NumberInputViewModel } from '../../FieldTypes';
import { FormStateService } from '../../services/form-state.service';

@Component({
  selector: 'app-number',
  templateUrl: './number.component.html'
})
export class NumberComponent implements OnInit {
  field: ValueFormField<NumberInputViewModel>;
  group: FormGroup;
  tracker: FormTracker;

  public constructor(private formState: FormStateService) { }

  public ngOnInit(): void { }

  onChange($event): void {
    let valid = true;
    const errorMessages = [];

    // custom client validation logic here
    if (this.field.model.required && !$event.target.value) {
      valid = false;
      errorMessages.push(`${this.field.model.title} is required`);
    }

    this.formState.setFieldState(this.field.valueField.name, $event.target.value, valid, errorMessages);
  }

  onFocus($event): void {
    this.tracker.onFocusField(this.field, $event.target.value);
  }

  onBlur($event): void {
    this.tracker.onBlurField(this.field, $event.target.value);
  }
}

<app-label [title]="field.model.title" [class]="field.model.labelCssClass"></app-label>
<input 
  type="number"
  [ngClass]="field.model.cssClass" 
  [id]="field.valueField.id" 
  [name]="field.valueField.name"
  [value]="field.model.value"
  [step]="field.model.step"
  [min]="field.model.min"
  [max]="field.model.max"
  (change)="onChange($event)"
  (focus)="onFocus($event)"
  (blur)="onBlur($event)">

<!-- <ng-container *ngFor="let validation of field.validations;" ngProjectAs="mat-error">
  <mat-error *ngIf="group.get(field.name).hasError(validation.name)">{{validation.message}}</mat-error>
</ng-container> -->
