// samples/nextjs/src/components/Styleguide-FieldUsage-File/index.tsx
import { File, Field, ComponentRendering, FileField } from '@sitecore-jss/sitecore-jss-nextjs';
import StyleguideSpecimen from '../Styleguide-Specimen';

interface StyleguideFieldUsageFileProps {
  fields: {
    heading: Field<string>;
    description: Field<string>;
    file: FileField;
  },
  rendering: ComponentRendering;
}

/**
 * Demonstrates usage of a File content field within JSS.
 * File types are stored within Sitecore's Media Library data, and can be edited.
 */
const StyleguideFieldUsageFile: React.FC<StyleguideFieldUsageFileProps> = (props) => (
  <StyleguideSpecimen {...props} e2eId="styleguide-fieldusage-file">
    {/* Renders a file link */}
    <File field={props.fields.file} />
    <br />

    {/* Renders a file link with a custom body and opening in a new tab */}
    <File field={props.fields.file} target="_blank">
      Custom link body
    </File>
  </StyleguideSpecimen>
);

export default StyleguideFieldUsageFile;

// packages/create-sitecore-jss/src/templates/angular/src/app/components/styleguide-field-usage-file/styleguide-field-usage-file.component.ts
import { Component, Input } from '@angular/core';
import { ComponentRendering } from '@sitecore-jss/sitecore-jss-angular';

/**
 * Demonstrates usage of a File content field within JSS.
 * File types are stored within Sitecore's Media Library data, and can be edited.
 */
@Component({
  selector: 'app-styleguide-field-usage-file',
  templateUrl: './styleguide-field-usage-file.component.html',
})
export class StyleguideFieldUsageFileComponent {
  @Input() rendering: ComponentRendering;
}

<app-styleguide-specimen [rendering]="rendering" e2eId="styleguide-fieldusage-file">
  <!-- Renders a file link -->
    <a *scFile="rendering.fields.file"></a>
    <br />

  <!-- Renders a file link with a custom body and opening in a new tab -->
  <a *scFile="rendering.fields.file" target="_blank">
    Custom link body
  </a>
</app-styleguide-specimen>
