// packages/create-sitecore-jss/src/templates/react/src/components/Styleguide-FieldUsage-ContentList/index.js
import React from 'react';
import { Text } from '@sitecore-jss/sitecore-jss-react';
import StyleguideSpecimen from '../Styleguide-Specimen';

/**
 * Demonstrates usage of a Content List field type within JSS.
 * Content Lists are references to 0..n other content items.
 * In Sitecore terms, this maps by default to a Treelist field.
 */
const StyleguideFieldUsageContentList = (props) => {
  const { sharedContentList, localContentList } = props.fields;

  return (
    <StyleguideSpecimen {...props} e2eId="styleguide-fieldusage-content-list">
      <h5>Shared Content List</h5>
      {/*
      Content list fields are returned with their value as an array of the referenced items.
      So we can use the .map() array function to traverse them. Ensure a `key` attribute is set
      on each element to make React's DOM updating happy:
     */}
      {sharedContentList &&
        sharedContentList.map((listItem, index) => (
          <div key={`sharedListItem-${index}`}>
            {/* The referenced item's fields can be rendered and edited using normal helper components: */}
            <p>
              Field: <Text field={listItem.fields.textField} />
            </p>
          </div>
        ))}

      <h5>Local Content List</h5>
      {localContentList &&
        localContentList.map((listItem, index) => (
          <div key={`localListItem-${index}`}>
            {/* The referenced item's fields can be rendered and edited using normal helper components: */}
            <p>
              Field: <Text field={listItem.fields.textField} />
            </p>
          </div>
        ))}
    </StyleguideSpecimen>
  );
};

export default StyleguideFieldUsageContentList;

// packages/create-sitecore-jss/src/templates/angular-sxp/src/app/components/styleguide-field-usage-content-list/styleguide-field-usage-content-list.component.ts
import { Component, Input } from '@angular/core';
import { ComponentRendering } from '@sitecore-jss/sitecore-jss-angular';

/**
 * Demonstrates usage of a Content List field type within JSS.
 * Content Lists are references to 0..n other content items.
 * In Sitecore terms, this maps by default to a Treelist field.
 */
@Component({
  selector: 'app-styleguide-field-usage-content-list',
  templateUrl: './styleguide-field-usage-content-list.component.html',
})
export class StyleguideFieldUsageContentListComponent {
  @Input() rendering: ComponentRendering;
}

<app-styleguide-specimen [rendering]="rendering" e2eId="styleguide-fieldusage-content-list">
  <h5>Shared Content List</h5>
  <!--
  Content list fields are returned with their value as an array of the referenced items.
  So we can use the .map() array function to traverse them. Ensure a `key` attribute is set
  on each element to make React's DOM updating happy:
  -->
  <ng-container *ngIf="rendering.fields.sharedContentList">
    <div *ngFor="let listItem of rendering.fields.sharedContentList">
      <!-- The referenced item's fields can be rendered and edited using normal helper components: -->
      <p>
        Field: <span *scText="listItem.fields.textField"></span>
      </p>
    </div>
  </ng-container>

  <h5>Local Content List</h5>
  <ng-container *ngIf="rendering.fields.localContentList">
    <div *ngFor="let listItem of rendering.fields.localContentList">
      <!-- The referenced item's fields can be rendered and edited using normal helper components: -->
      <p>
        Field: <span *scText="listItem.fields.textField"></span>
      </p>
    </div>
  </ng-container>
</app-styleguide-specimen>
