// samples/basic-sample-vue-web/src/app/App.vue
<template>
  <div>
    <placeholder name="main" :rendering="route" />
  </div>
</template>

<script>
import { Placeholder } from '@sitecore-jss/sitecore-jss-vue';
import '../../assets/css/default.css';

export default {
  name: 'App',
  props: {
    route: {
      type: Object,
      default: () => ({}),
    },
  },
  components: {
    Placeholder,
  },
};
</script>

<style>

</style>

// samples/embedded-wizard-sample-react/src/app/components/App.js
import React from 'react';
import { SitecoreContext, Placeholder } from '@sitecore-jss/sitecore-jss-react';
import componentFactory from '../componentFactory';

import 'assets/css/app.css';

const App = ({sitecoreState}) =>
    <SitecoreContext componentFactory={componentFactory}>
        <Placeholder name="main" rendering={sitecoreState.sitecore.route} context={sitecoreState.sitecore.context} />
    </SitecoreContext>
    
export default App;
