// packages/create-sitecore-jss/src/templates/nextjs-personalize/src/components/CdpPageView.tsx
import {
  CdpHelper,
  LayoutServicePageState,
  SiteInfo,
  useSitecoreContext,
  PosResolver,
} from '@sitecore-jss/sitecore-jss-nextjs';
import { useEffect } from 'react';
import config from 'temp/config';
import { init } from '@sitecore/engage';
import { siteResolver } from 'lib/site-resolver';

/**
 * This is the CDP page view component.
 * It uses the Sitecore Engage SDK to enable page view events on the client-side.
 * See Sitecore Engage SDK documentation for details.
 * https://www.npmjs.com/package/@sitecore/engage
 */
const CdpPageView = (): JSX.Element => {
  const {
    sitecoreContext: { pageState, route, variantId, site },
  } = useSitecoreContext();

  /**
   * Creates a page view event using the Sitecore Engage SDK.
   */
  const createPageView = async (
    page: string,
    language: string,
    site: SiteInfo,
    pageVariantId: string
  ) => {
    const pointOfSale = PosResolver.resolve(site, language);
    const engage = await init({
      clientKey: process.env.NEXT_PUBLIC_CDP_CLIENT_KEY || '',
      targetURL: process.env.NEXT_PUBLIC_CDP_TARGET_URL || '',
      // Replace with the top level cookie domain of the website that is being integrated e.g ".example.com" and not "www.example.com"
      cookieDomain: window.location.host.replace(/^www\./, ''),
      // Cookie may be created in personalize middleware (server), but if not we should create it here
      forceServerCookieMode: false,
    });
    engage.pageView({
      channel: 'WEB',
      currency: 'USD',
      pointOfSale,
      page,
      pageVariantId,
      language,
    });
  };

  /**
   * Determines if the page view events should be turned off.
   * IMPORTANT: You should implement based on your cookie consent management solution of choice.
   * By default it is disabled in development mode
   */
  const disabled = () => {
    return process.env.NODE_ENV === 'development';
  };

  useEffect(() => {
    // Do not create events in editing or preview mode or if missing route data
    if (pageState !== LayoutServicePageState.Normal || !route?.itemId) {
      return;
    }
    // Do not create events if disabled (e.g. we don't have consent)
    if (disabled()) {
      return;
    }

    const siteInfo = siteResolver.getByName(site?.name || config.jssAppName);
    const language = route.itemLanguage || config.defaultLanguage;
    const scope = process.env.NEXT_PUBLIC_PERSONALIZE_SCOPE;

    const pageVariantId = CdpHelper.getPageVariantId(route.itemId, language, variantId as string, scope);
    createPageView(route.name, language, siteInfo, pageVariantId);
  }, [pageState, route, variantId, site]);

  return <></>;
};

export default CdpPageView;

// packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/routing/scripts/cdp-page-view.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs';
import { isServer, CdpHelper, LayoutServicePageState } from '@sitecore-jss/sitecore-jss-angular';
import { pageView, PageViewData } from '@sitecore-cloudsdk/events/browser';
import { JssContextService } from '../../jss-context.service';
import { JssState } from '../../JssState';
import { environment } from '../../../environments/environment';

/**
 * This is the CDP page view component.
 * It uses the Sitecore Cloud SDK to enable page view events on the client-side.
 * See Sitecore Cloud SDK documentation for details.
 * https://www.npmjs.com/package/@sitecore-cloudsdk/events
 */
@Component({
  selector: 'app-cdp-page-view',
  template: '',
})
export class CdpPageViewComponent implements OnInit, OnDestroy {
  private contextSubscription: Subscription;

  constructor(private jssContext: JssContextService) {}

  ngOnInit(): void {
    if (!isServer()) {
      this.contextSubscription = this.jssContext.state.subscribe((newState: JssState) => {
        const {
          route,
          context: { pageState, language, variantId },
        } = newState.sitecore;
// Do not create events in editing or preview mode or if missing route data
        if (pageState !== LayoutServicePageState.Normal || !route?.itemId) {
          return;
        }

        // Do not create events if disabled (e.g. we don't have consent)
        if (this.disabled()) {
          return;
        }

        const scope = process.env.ANGULAR_PUBLIC_PERSONALIZE_SCOPE;
        const pageVariantId = CdpHelper.getPageVariantId(
          route.itemId,
          language || environment.defaultLanguage,
          variantId as string,
          scope
        );

        const pageViewData: PageViewData = {
          channel: 'WEB',
          currency: 'USD',
          page: route.name,
          pageVariantId,
          language,
        };

        pageView(pageViewData).catch((err) => console.debug(err));
      });
    }
  }

  ngOnDestroy() {
    if (this.contextSubscription) {
      this.contextSubscription.unsubscribe();
    }
  }

  /**
   * Determines if the page view events should be turned off.
   * IMPORTANT: You should implement based on your cookie consent management solution of choice.
   * By default it is disabled if not in production mode
   */
  disabled = () => {
    return !environment.production;
  };
}
