// samples/vue/src/components/Styleguide/Styleguide-CustomRouteType.vue
<!--
  Demonstrates gaining access to root route-level data from within components.
-->
<template>
  <div data-e2e-id="styleguide-customroutetype">
    <sc-text tag="h3" :field="routeData.fields.headline" />

    <p>
      <em>
        By <sc-text :field="routeData.fields.author" />
      </em>
    </p>

    <sc-rich-text :field="routeData.fields.content" />

    <router-link to="/styleguide">Return to the Styleguide</router-link>
  </div>
</template>

<script>
import { Text, RichText } from '@sitecore-jss/sitecore-jss-vue';

export default {
  name: 'Styleguide-CustomRouteType',
  props: {
    fields: {
      type: Object,
    },
    rendering: {
      type: Object,
    },
  },
  components: {
    ScText: Text,
    ScRichText: RichText,
  },
  computed: {
    routeData() {
      // this.$jss is defined on the Vue instance by the SitecoreJssPlugin and provides
      // reactive access to the root level route data provided in layout service data.
      return this.$jss.routeData();
    },
  },
};
</script>

// samples/react/src/components/Styleguide-CustomRouteType/index.js
import React from 'react';
import { Link } from 'react-router-dom';
import { withSitecoreContext, Text, RichText } from '@sitecore-jss/sitecore-jss-react';

// this fancy destructure syntax is essentially equivalent to
// const fields = props.sitecoreContext.route.fields
const StyleguideCustomRouteType = ({
  sitecoreContext: {
    route: { fields },
  },
}) => (
  <div data-e2e-id="styleguide-customroutetype">
    <Text tag="h3" field={fields.headline} />

    <p>
      <em>
        By <Text field={fields.author} />
      </em>
    </p>

    <RichText field={fields.content} />

    <Link to="/styleguide">Return to the Styleguide</Link>
  </div>
);

// withSitecoreContext() is the magical glue that gives you route-level context access
// see the context examples in the styleguide for more details.
export default withSitecoreContext()(StyleguideCustomRouteType);
