// packages/create-sitecore-jss/src/templates/angular/src/app/routing/not-found/not-found.component.ts
import { Component, Input } from '@angular/core';
import { LayoutServiceContextData } from '@sitecore-jss/sitecore-jss-angular';

@Component({
  selector: 'app-not-found',
  templateUrl: './not-found.component.html'
})
export class NotFoundComponent {
  @Input() errorContextData: LayoutServiceContextData;
}

<h1>Not found</h1>
<p>This page does not exist.</p>
<p>
  Site: {{errorContextData?.context?.site?.name}}
  <br />
  Language: {{errorContextData?.context?.language}}
</p>

// samples/vue/src/NotFound.vue
<template>
  <div>
    <h1>Page not found</h1>
    <p>This page does not exist.</p>
    <p v-if="context && context.site">
      Site: {{context.site.name}}
      <br />
      Language: {{context.language}}
    </p>
  </div>
</template>

<script>
export default {
  name: 'not-found',
  metaInfo() {
    return {
      title: this.$t('page-not-found'),
    };
  },
  props: {
    context: {
      type: Object,
    },
  },
};
</script>
