// packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/link-list/link-list.component.ts
import { Component, OnInit } from '@angular/core';
import { SxaComponent } from '../sxa.component';
import { Field, LinkField, SxaLinkListFields } from '@sitecore-jss/sitecore-jss-angular';

@Component({
  selector: 'app-link-list',
  templateUrl: './link-list.component.html',
})
export class LinkListComponent extends SxaComponent<SxaLinkListFields> implements OnInit {
  title?: Field<string>;
  fieldLinks: LinkField[] = [];

  getFieldLinkClass(index: number): string {
    let className = `item${index}`;
    className += (index + 1) % 2 == 0 ? ' even' : ' odd';
    if (index === 0) {
      className += ' first';
    }
    if (index + 1 === this.fieldLinks.length) {
      className += ' last';
    }
    return className;
  }

  ngOnInit() {
    super.ngOnInit();
    const datasource = this.rendering.fields?.data?.datasource;
    if (datasource) {
      this.title = datasource.field?.title as Field<string>;
      datasource.children.results.forEach(item => {
        if (item.field?.link)
          this.fieldLinks.push(item.field.link as LinkField);
      });
    }
  }
}

<div class="component link-list {{ styles }}" [attr.id]="id">
  <div class="component-content">
    <ng-container *ngIf="title; else defaultTitle">
      <h3 *scText="title"></h3>
    </ng-container>    
    <ul>
      <li *ngFor="let fieldLink of fieldLinks;index as i" [ngClass]="getFieldLinkClass(i)" >
        <div class="field-link">
          <a *scLink="fieldLink"></a>
        </div>
      </li>
    </ul>
  </div>
  <ng-template #defaultTitle>
    <span class="is-empty-hint">Link list</span>
  </ng-template>
</div>

// packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/LinkList.tsx
import React from 'react';
import {
  Link as JssLink,
  Text,
  LinkField,
} from '@sitecore-jss/sitecore-jss-nextjs';
import { TextField } from '@sitecore-jss/sitecore-jss-react';

interface Fields {
  data: Object & {
    datasource: Object & {
      children: Object & {
        results: Array<any> & {
          field: Object & {
            link: LinkField;
          };
        };
      };
      field: Object & {
        title: TextField;
      };
    };
  };
}

type LinkListProps = {
  params: { [key: string]: string };
  fields: Fields;
};

const LinkListItem = (props: any) => {
  let className = `item${props.index}`;
  (props.index + 1) % 2 == 0 ? (className += ' odd') : (className += ' even');
  if (props.index == 0) {
    className += ' first';
  }
  if (props.index + 1 == props.total) {
    className += ' last';
  }
  return (
    <li className={className}>
      <div className="field-link">
        <JssLink field={props.field} />
      </div>
    </li>
  );
};

export const Default = (props: LinkListProps): JSX.Element => {
  let datasource = props.fields?.data?.datasource;
  if (datasource) {
    let list = [];
    for (let i = 0; i < datasource.children.results.length; i++) {
      let element = datasource.children.results[i].field.link;
      if (element) {
        list.push(
          <LinkListItem
            index={i}
            key={i}
            total={datasource.children.results.length}
            field={element}
          />
        );
      }
    }
    return (
      <div className={`component link-list ${props.params.styles?.replace(/\|/g, ' ')}`}>
        <div className="component-content">
          <Text tag="h3" field={datasource?.field?.title} />
          <ul>{list}</ul>
        </div>
      </div>
    );
  } else {
    return (
      <div className={`component link-list ${props.params.styles?.replace(/\|/g, ' ')}`}>
        <div className="component-content">
          <h3>Link List</h3>
        </div>
      </div>
    );
  }
};
