// samples/nuxtjs/components/Styleguide/Styleguide-RouteFields.vue
<!--
  Demonstrates gaining access to route-level fields.
  This technique builds on the Styleguide-SitecoreContext technique,
  to also get the route level field data and make it editable.
-->
<template>
  <styleguide-specimen v-bind="$props" data-e2e-id="styleguide-route-fields">
    <p>
      Route level <code>pageTitle</code> field:&nbsp;
      <sc-text :field="ssrInitialState.routeData.fields.pageTitle" />
    </p>
    <p>
      <a href="/styleguide/custom-route-type"
        >Sample of using a custom route type</a
      >
    </p>
  </styleguide-specimen>
</template>
<script setup>
const ssrInitialState = useState('ssrInitialState');
</script>
<script>
import { Text } from '@sitecore-jss/sitecore-jss-vue';
import StyleguideSpecimen from './Styleguide-Specimen';

export default {
  name: 'Styleguide-RouteFields',
  props: {
    fields: {
      type: Object,
    },
    rendering: {
      type: Object,
    },
  },
  components: {
    StyleguideSpecimen,
    ScText: Text,
  },
};
</script>

// samples/nextjs/src/components/Styleguide-RouteFields/index.tsx
import Link from 'next/link';
import {
  Field,
  ComponentRendering,
  withSitecoreContext,
  Text,
  RouteData,
} from '@sitecore-jss/sitecore-jss-nextjs';
import StyleguideSpecimen from 'components/Styleguide-Specimen';

interface RouteFieldsRouteData extends RouteData {
  fields: {
    pageTitle: Field<string>;
  };
}

interface StyleguideRouteFieldsProps {
  fields: {
    heading: Field<string>;
    description: Field<string>;
  };
  rendering: ComponentRendering;
  sitecoreContext: {
    route: RouteFieldsRouteData;
  };
}

/**
 * Demonstrates gaining access to route-level fields.
 * This technique builds on the Styleguide-SitecoreContext technique,
 * to also get the route level field data and make it editable.
 */
const StyleguideRouteFields: React.FC<StyleguideRouteFieldsProps> = (props) => (
  <StyleguideSpecimen {...props} e2eId="styleguide-route-fields">
    <p>
      Route level <code>pageTitle</code> field:{' '}
      {props.sitecoreContext.route && <Text field={props.sitecoreContext.route.fields.pageTitle} />}
    </p>
    <p>
      <Link href="/styleguide/custom-route-type">
        <a>Sample of using a custom route type</a>
      </Link>
    </p>
  </StyleguideSpecimen>
);

export default withSitecoreContext()(StyleguideRouteFields);
