// samples/react/src/components/Form/field-templates/dropdown-list.js
import React from 'react';
import FieldValidationErrors from './field-validation-errors';
import Label from './label';

function DropdownList({ field, value, isValid, errors, onChange }) {
  const items = field.model.items;

  // note: the value for list field types is an array (of selected values)
  // dropdown is single-select so we use value[0] for its value

  return (
    <React.Fragment>
      <Label field={field} isValid={isValid} />
      <select
        className={field.model.cssClass}
        id={field.valueField.id}
        name={field.valueField.name}
        value={value[0]}
        onChange={(e) => handleOnChange(field, e.target.value, onChange)}
      >
        {field.model.showEmptyItem ? <option label=" " /> : null}
        {items.map((item) => (
          <option key={item.itemId} value={item.value}>
            {item.text}
          </option>
        ))}
      </select>

      <FieldValidationErrors errors={errors} />
    </React.Fragment>
  );
}

function handleOnChange(field, newValue, callback) {
  let valid = true;
  const errorMessages = [];

  // custom client validation logic here
  if (field.model.required && !newValue) {
    valid = false;
    errorMessages.push(`${field.model.title} is required`);
  }

  callback(field.valueField.name, [newValue], valid, errorMessages);
}

export default DropdownList;

// packages/sitecore-jss-angular-forms/src/app/components/forms/fields/dropdown-list/dropdown-list.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { ValueFormField, DropdownListViewModel, ListFieldItem, FormTracker } from '@sitecore-jss/sitecore-jss-forms';
import { FormStateService } from '../../services/form-state.service';

@Component({
  selector: 'app-dropdown-list',
  templateUrl: './dropdown-list.component.html',
  styleUrls: ['./dropdown-list.component.scss']
})
export class DropdownListComponent implements OnInit {
  field: ValueFormField<DropdownListViewModel>;
  group: FormGroup;
  tracker: FormTracker;

  public items: ListFieldItem[];

  public constructor(private formState: FormStateService) { }

  public ngOnInit(): void {
    this.items = this.field.model.items;
  }

  onChange($event): void {
    let valid = true;
    const errorMessages = [];

    // custom client validation logic here
    if (this.field.model.required && !$event.target.value) {
      valid = false;
      errorMessages.push(`${this.field.model.title} is required`);
    }

    this.formState.setFieldState(this.field.valueField.name, $event.target.value, valid, errorMessages);
  }

  onFocus($event): void {
    this.tracker.onFocusField(this.field, <string>this.field.model.value);
  }

  onBlur($event): void {
    this.tracker.onBlurField(this.field, <string>this.field.model.value);
  }
}

<app-label [title]="field.model.title" [class]="field.model.labelCssClass"></app-label>
<select 
  [ngClass]="field.model.cssClass" 
  [id]="field.valueField.id" 
  [name]="field.valueField.name"
  [value]="field.model.value"
  (change)="onChange($event)" 
  (focus)="onFocus($event)" 
  (blur)="onBlur($event)">
  <option *ngIf="field.model.showEmptyItem"></option>
  <option *ngFor="let option of items;" [value]="option.value">
    {{option.text}}
  </option>
</select>
