// packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/RichText.tsx
import { JSX } from 'react';
import { Field, RichText as JssRichText } from '@sitecore-jss/sitecore-jss-nextjs';

interface Fields {
  Text: Field<string>;
}

export type RichTextProps = {
  params: { [key: string]: string };
  fields: Fields;
};

export const Default = (props: RichTextProps): JSX.Element => {
  const text = props.fields ? (
    <JssRichText field={props.fields.Text} />
  ) : (
    <span className="is-empty-hint">Rich text</span>
  );
  const id = props.params.RenderingIdentifier;

  return (
    <div
      className={`component rich-text ${props.params.styles.trimEnd()}`}
      id={id ? id : undefined}
    >
      <div className="component-content">{text}</div>
    </div>
  );
};

// packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/richtext/richtext.component.ts
﻿import { Component, Input, OnInit } from '@angular/core';
import { ComponentRendering } from '@sitecore-jss/sitecore-jss-angular';

@Component({
  selector: 'app-richtext',
  templateUrl: './richtext.component.html',
})
export class RichTextComponent implements OnInit {
  @Input() rendering: ComponentRendering;
  text: string;
  id: string;
  styles: string;

  ngOnInit() {
    this.text = this.rendering.fields.Text;
    this.id = this.rendering.params.RenderingIdentifier;
    this.styles = this.rendering.params?.styles?.trimEnd();
  }
}

﻿<div
  class="component rich-text {{ styles }}"
  [attr.id]="id"
>
  <div class="component-content">
    <ng-container *ngIf="text; else emptyHint">
      <div *scRichText="text"></div>
    </ng-container>
    <ng-template #emptyHint>
      <span class="is-empty-hint">Rich text</span>
    </ng-template>
  </div>
</div>
