// packages/create-sitecore-jss/src/templates/nextjs-sxa/src/components/ColumnSplitter.tsx
import React from 'react';
import {
  ComponentParams,
  ComponentRendering,
  Placeholder,
} from '@sitecore-jss/sitecore-jss-nextjs';

interface ComponentProps {
  rendering: ComponentRendering & { params: ComponentParams };
  params: ComponentParams;
}

export const Default = (props: ComponentProps): JSX.Element => {
  const styles = `${props.params.GridParameters ?? ''} ${props.params.Styles ?? ''}`.trimEnd();
  const columnWidths = [
    props.params.ColumnWidth1,
    props.params.ColumnWidth2,
    props.params.ColumnWidth3,
    props.params.ColumnWidth4,
    props.params.ColumnWidth5,
    props.params.ColumnWidth6,
    props.params.ColumnWidth7,
    props.params.ColumnWidth8,
  ];
  const columnStyles = [
    props.params.Styles1,
    props.params.Styles2,
    props.params.Styles3,
    props.params.Styles4,
    props.params.Styles5,
    props.params.Styles6,
    props.params.Styles7,
    props.params.Styles8,
  ];
  const enabledPlaceholders = props.params.EnabledPlaceholders.split(',');

  return (
    <div className={`row component column-splitter ${styles}`}>
      {enabledPlaceholders.map((ph, index) => {
        const phKey = `column-${ph}-{*}`;
        const phStyles = `${columnWidths[+ph - 1]} ${columnStyles[+ph - 1] ?? ''}`.trimEnd();

        return (
          <div key={index} className={phStyles}>
            <div key={index} className="row">
              <Placeholder key={index} name={phKey} rendering={props.rendering} />
            </div>
          </div>
        );
      })}
    </div>
  );
};

// packages/create-sitecore-jss/src/templates/angular-xmcloud/src/app/components/column-splitter/column-splitter.component.ts
﻿import { Component, OnInit } from '@angular/core';
import { SxaComponent } from '../sxa.component';

@Component({
  selector: 'app-column-splitter',
  templateUrl: './column-splitter.component.html',
})
export class ColumnSplitterComponent extends SxaComponent implements OnInit {
  ngOnInit() {
    super.ngOnInit();
  }

  get columnSplitterStyles(): string {
    return `${this.rendering.params.GridParameters ?? ''} ${this.rendering.params.Styles ??
      ''}`.trimEnd();
  }

  get columnWidths(): string[] {
    return [
      this.rendering.params.ColumnWidth1,
      this.rendering.params.ColumnWidth2,
      this.rendering.params.ColumnWidth3,
      this.rendering.params.ColumnWidth4,
      this.rendering.params.ColumnWidth5,
      this.rendering.params.ColumnWidth6,
      this.rendering.params.ColumnWidth7,
      this.rendering.params.ColumnWidth8,
    ];
  }

  get columnStyles(): string[] {
    return [
      this.rendering.params.Styles1,
      this.rendering.params.Styles2,
      this.rendering.params.Styles3,
      this.rendering.params.Styles4,
      this.rendering.params.Styles5,
      this.rendering.params.Styles6,
      this.rendering.params.Styles7,
      this.rendering.params.Styles8,
    ];
  }

  get enabledPlaceholders(): string[] {
    return this.rendering.params.EnabledPlaceholders.split(',');
  }
}

﻿<div [ngClass]="['row', 'component', 'column-splitter', columnSplitterStyles]" [attr.id]="id || null">
  <div *ngFor="let ph of enabledPlaceholders; let index = index">
    <div [ngClass]="[columnWidths[+ph - 1], columnStyles[+ph - 1] || ''].join(' ').trim()">
      <div [ngClass]="['row']">
        <sc-placeholder
          [key]="index"
          [name]="'column-' + ph + '-{*}'"
          [rendering]="rendering">
        </sc-placeholder>
      </div>
    </div>
  </div>
</div>
