// packages/create-sitecore-jss/src/templates/react/src/components/Styleguide-EditFrame/index.js
import React from 'react';
import { EditFrame } from '@sitecore-jss/sitecore-jss-react';
import StyleguideSpecimen from '../Styleguide-Specimen';

const StyleguideEditFrame = (props) => (
  <StyleguideSpecimen {...props} e2eId="styleguide-editframe">
    <EditFrame {...getEditFrameProps(props.rendering.dataSource)}>
      Who framed Roger Rabbit? Hard to say. <br />
      But JSS now allows to edit frame any piece of content on a page in editing mode. <br />
      You can add web edit or field edit buttons, modify edit frame style through CSS class and
      put the frame wherever you need it.
      {props.children}
    </EditFrame>
  </StyleguideSpecimen>
);

const getEditFrameProps = (dataSource) => {
  return {
    dataSource: dataSource
      ? {
          itemId: dataSource,
          // databaseName: 'web',
          // language: 'en', // optional params you can also set for datasource
        }
      : undefined, // datasource will set the item to be edited by edit frame
    buttons: editFrameButtons, // add custom editing functionality or edit field sets with buttons
    title: 'JSS edit frame',
    tooltip: 'Perform editing anywhere while not tied to a rendering, placeholder or field',
    cssClass: 'jss-edit-frame', // customize edit frame appearance through CSS
    parameters: {}, // set additional parameters when needed
  };
};

const editFrameButtons = [
  {
    header: 'WebEditButton',
    icon: '/~/icon/Office/16x16/document_selection.png',
    click: 'javascript:alert("An edit frame button was just clicked!")',
    tooltip: 'Doesnt do much, just a web edit button example',
  }, // use javascript:, webedit: or chrome: commands for webedit buttons
  {
    header: 'FieldEditButton',
    icon: '/~/icon/Office/16x16/pencil.png',
    fields: ['heading'],
    tooltip: 'Allows you to open field editor for specified fields',
  }, // or use field edit buttons to open Field Editor
];

export default StyleguideEditFrame;

// packages/create-sitecore-jss/src/templates/angular/src/app/components/styleguide-edit-frame/styleguide-edit-frame.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { ComponentRendering, EditFrameDataSource, FieldEditButton, LayoutServiceContextData, RouteData, WebEditButton } from '@sitecore-jss/sitecore-jss-angular';
import { JssContextService } from '../../jss-context.service';

interface EditFrameProps {
  dataSource: EditFrameDataSource,
  buttons: (FieldEditButton | WebEditButton | '|')[],
  title: string,
  tooltip: string,
  cssClass: string,
  parameters: object,
}

@Component({
  selector: 'app-styleguide-edit-frame',
  templateUrl: './styleguide-edit-frame.component.html',
})
export class StyleguideEditFrameComponent implements OnInit {
  @Input() rendering: ComponentRendering;
  context:  LayoutServiceContextData & {
    route: RouteData<unknown> | null;
  };

  editFrameProps: EditFrameProps;

  constructor(private jssContext: JssContextService) { }

  ngOnInit() {
    this.jssContext.state.subscribe((state) => {
      this.context = state.sitecore;
    });
    this.editFrameProps = this.getEditFrameProps(this.rendering.dataSource);
  }

  getEditFrameProps(dataSource: string) {
    return {
      dataSource: dataSource
        ? {
            itemId: dataSource,
            // databaseName: 'web',
            // language: 'en', // optional params you can also set for datasource
          }
        : undefined, // datasource will set the item to be edited by edit frame
      buttons: this.editFrameButtons, // add custom editing functionality or edit field sets with buttons
      title: 'JSS edit frame',
      tooltip: 'Perform editing anywhere while not tied to a rendering, placeholder or field',
      cssClass: 'jss-edit-frame', // customize edit frame appearance through CSS
      parameters: {}, // set additional parameters when needed
      sitecore: this.context,
    };
  };
  
  editFrameButtons = [
    {
      header: 'WebEditButton',
      icon: '/~/icon/Office/16x16/document_selection.png',
      click: 'javascript:alert("An edit frame button was just clicked!")',
      tooltip: 'Doesnt do much, just a web edit button example',
    }, // use javascript:, webedit: or chrome: commands for webedit buttons
    {
      header: 'FieldEditButton',
      icon: '/~/icon/Office/16x16/pencil.png',
      fields: ['heading'],
      tooltip: 'Allows you to open field editor for specified fields',
    }, // or use field edit buttons to open Field Editor
  ];
}

<app-styleguide-specimen [rendering]="rendering" e2eId="styleguide-edit-frame">
  <h4 *scText="rendering.fields.heading"></h4>
  <sc-edit-frame [dataSource]="editFrameProps.dataSource"
    [buttons]="editFrameProps.buttons"
    [title]="editFrameProps.title"
    [tooltip]="editFrameProps.tooltip"
    [cssClass]="editFrameProps.cssClass"
    [parameters]="editFrameProps.parameters"
    [sitecore]="context">
    Who framed Roger Rabbit? Can't say. <br/>
    But JSS now allows to edit frame any piece of content on a page in editing mode. <br />
    You can add web edit or field edit buttons, modify edit frame's style through CSS class and put the frame wherever you need it
    <ng-content></ng-content>
  </sc-edit-frame>
</app-styleguide-specimen
